### ISSUE TITLE
首页与架构改版

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-motion#10]
- [x] 首页改版
- [x] 网站架构调整
  - [x] 信息结构 
  - [x] 页面逻辑
  - [x] 功能区块重新整理

- [x] 模板这块提供下载

- [x] 添加页面加载动画

- [ ] 404页面设计

- [x] scollAnim 内容更新

- [x] load 在 windows 下变量错误 ，不能用t

- [ ] 动效demo 6个。

后期再整：

- [ ] 小动画编辑器

- [ ] 可视化编辑忧化。
  左侧导航。
 - [ ] 可添加删除模块。
 - [ ] 对背景处理。
 - [ ] 调整页面布局和添加区块
 - [ ] 其它功能编辑

  双击开启编辑后：
 - [ ] 拖动可编辑位置，百分比变成绝对值。
 - [ ] 双击后编辑区块内容
 - [ ] 调整样式

**Comment by Ceinsgrimm** [comment]
nice shot!

**Comment by hi-caicai** [comment]
Ant Design 全面开始翻译工作了，是否我们这次改版，直接上英文版本？

**Comment by jljsj33** [comment]
人啊没几个，，翻译个卵，，先去推。。。

**Comment by JuelChiang** [comment]
这次直接中英文两版来设计？

**Comment by jayguojianhai** [comment]
不支持ie8怎么破？

**Comment by jljsj33** [comment]
@jayguojianhai react 都要放弃 ie8 了。。。破不了

**Comment by jayguojianhai** [comment]
@jljsj33  整屏滚动加右边小点点 功能加上去以后 滚动条滚动很不流畅，有卡顿跟延迟现象

**Comment by jljsj33** [comment]
@jayguojianhai demo 里还好啊， http://react-component.github.io/scroll-anim/examples/link.html， 你看下demo 里的卡?
