### ISSUE TITLE
QueueAnim 组件不能重复渲染组件

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-motion#100]
### 环境
 win10 + chrome + antd-mobile1.4.2
### 场景 
一种情况下，会重复渲染一个组件。
### 期望
页面组件正常，动画效果正常
### 实际
QueueAnim 报错导致组件不能渲染
### 重现
https://codepen.io/anon/pen/LLqLPz?editors=0010

**Comment by jljsj33** [comment]
https://github.com/react-component/queue-anim/issues/35

**Comment by jljsj33** [comment]
3. 多次 render 处理，currentChildren 用 state.children,判断当前显示元素与 nextChildren 对比.

你可以PR 或等下个版本更新下。

**Comment by jljsj33** [comment]
你这个不是重复渲染的问题，，我看了下，，是不支持 height: 0 的问题，目前数据只能这么写,, 
```jsx
animConfig={[
              { opacity: [1, 0], translateY: [0, 30] },
              { height: [100, 0] },
            ]}
```

**Comment by zjxpcyc** [comment]
@jljsj33  ok, thx

**Comment by jljsj33** [comment]
下版本支持。。。

**Comment by jljsj33** [comment]
v1.1.0支持了

**Comment by zjxpcyc** [comment]
thx

**Comment by jljsj33** [comment]
queue-anim v1.1.0 支持了。。。。ant motion 的版本是网站的静态网页版本，不是跟 ant design 那样的是集合所有组件的版本。。。所以，你最好再关注的每个动画组件的版本。。。

**Comment by jljsj33** [comment]
https://github.com/react-component/queue-anim
