### ISSUE TITLE
Some initial styles doesn't work

### ISSUE THREAD

**Issue by Feel-Joy** [ant-design/ant-motion#101]
我在 `Home Component` 中绘制了一个canvas元素，为了在加载这个元素时能有一些动态效果，我使用了 `rc-tween-anim@1.2.9`；
这是我的 `Home component`：
```jsx
import React, {PureComponent} from 'react'; // @15.6.1
import {TweenOneGroup} from 'rc-tween-one'; // @1.2.9

import cssModule from 'react-css-modules'; // @4.5.2
import styles from './Home.css';

@cssModule(styles)
export default class Home extends PureComponent {

  componentDidMount() {
    this.drawMac();
  }

  drawMac = () => { //use some code to draw a mac };

  render() {
    return(
      <div>
        <TweenOneGroup enter={{x: 50, y: 50, opacity: 0, type: 'from', ease: 'easeOutQuint'}}>
          <canvas key='0' width={400} height={230} id="mac" styleName="mac"/>
        </TweenOneGroup>
      </div>
    )
  }
}
```
之后我为这个canvas元素添加了样式：
```css
.mac {
  transform: rotate(30deg);
}
```
**运行这段代码时发现我在css中设置的 `transform` 属性没有生效，貌似是被 `rc-tween-anim` 覆盖了。
那么我应该如何为元素添加一个初始的 `transform` 属性呢？**

**Comment by jljsj33** [comment]
没有styleName这属性，你用 className 或css里用 #mac

**Comment by Feel-Joy** [comment]
@jljsj33 由于我在项目中使用了 `react-css-module@4.5.2`，[https://github.com/gajus/react-css-modules#whats-the-problem](url)，因此会使用 `styleName` 为元素添加类名；
.mac 中的样式会被添加到元素上，但 `transform` 属性会被覆盖；
如果我想为元素添加一个初始的旋转角度（默认的，且不需要动画效果），并且与 `rc-tween-anim` 不冲突，可以实现吗？
我暂时的处理方法是在canvas元素外套一层div，.mac 为canvas添加默认的旋转角度，`rc-tween-anim` 控制div的动画效果。不知道有没有更好的实现方式 :)

**Comment by jljsj33** [comment]
又是 css-module。。。。


不可能冲突的啊。。。我这没问题啊
![image](https://user-images.githubusercontent.com/6802825/28255897-3d7f797c-6aef-11e7-9073-745569aefb49.png)

还有个方案就是你直接在 canvas 上加 style={{ transform: 'rotate(30deg)'}}

**Comment by Feel-Joy** [comment]
@jljsj33 我这里的情况是在首次加载时不会生效，之后再次加载（例如切换路由）则会生效；

**Comment by jljsj33** [comment]
https://codepen.io/jljsj33/pen/RpjQvw 提供下 demo 看看。。。

**Comment by Feel-Joy** [comment]
@jljsj33 Hello! 我在使用 codePen 时遇到了一个问题，transform 属性不生效，不论是写在 css 文件中还是写在内联样式中，请问你有遇到过相同的问题么。

**Comment by jljsj33** [comment]
不生效的地址发出来看看 @Feel-Joy

**Comment by Feel-Joy** [comment]
@jljsj33 https://codepen.io/Feel-Joy/pen/QgRqom

**Comment by jljsj33** [comment]
```jsx
<TweenOne animation={ {x:  300 }} style={{ transform: 'rotate(-20deg)' }}>test</TweenOne>
```

**Comment by jljsj33** [comment]
animation 里不是给你设置 style 样式的。。。

animation 里支持这些东西。。你可以看下 。。。https://motion.ant.design/language/animate-term

如果你非要在 animation 里设置开始，，你可以这样

```jsx
<TweenOne animation={ [ { rotate: -20, duration: 0 }, { x:  300 } ]} style={{ transform: 'rotate(-20deg)' }}>test</TweenOne>
```

**Comment by Feel-Joy** [comment]
@jljsj33 问题已解决，感谢 : )
