### ISSUE TITLE
SvgDrawPlugin example doesn't work

### ISSUE THREAD

**Issue by lzmhhh123** [ant-design/ant-motion#102]
`import SvgDrawPlugin from 'rc-tween-one/lib/plugin/SvgDrawPlugin';
TweenOne.plugins.push(SvgDrawPlugin);
<TweenOne animation={{ SVGDraw: 0 }} />`
This example return such a error.

**TypeError: this.target.getTotalLength is not a function
SvgDrawPlugin.getAnimStart
node_modules/rc-tween-one/lib/plugin/SvgDrawPlugin.js:86**
>  83 |     this.length = this.getEllipseLength();
>  84 |     break;
>  85 |   default:
>  86 |     **this.length = this.target.getTotalLength();**
>  87 |     break;
>  88 | }
>  89 | this.length = parseFloat(this.length.toFixed(3));

**Comment by jljsj33** [comment]
这个只针对 svg 里的标签的。。。TweenOne 默认 component 是 div；暂时不支持 div 框的动画。。。

[SvgDrawPlugin deom](http://react-component.github.io/tween-one/examples/svgDraw.html)
