### ISSUE TITLE
any plan to internationalize the motion page builder?

### ISSUE THREAD

**Issue by neekey** [ant-design/ant-motion#106]
Hi, I just found your page builder https://motion.ant.design/edit/, very cool. I am wondering if you have any plan to make a english version ?

**Comment by jljsj33** [comment]
If you can. PR welcome.

**Comment by renatorib** [comment]
@jljsj33 I know PRs are welcome. Always are. I think the main question is if you have **any plan** to it, and not a request itself

**Comment by jljsj33** [comment]
yes，we do have a plan for english version，but it takes time：）I'll tell you if its ready.

**Comment by renatorib** [comment]
Nice! Good to read it. Good lucky, you have a nice project in your hands.

**Comment by Ehesp** [comment]
If you guys can get a start going on how you'd go about doing this, I'm sure the community will help with the translations. Just a tricky one knowing how you guys want it implemented.

**Comment by jljsj33** [comment]
https://landing.ant.design/edit/
