### ISSUE TITLE
如何触发子组件的离场动画？

### ISSUE THREAD

**Issue by Feel-Joy** [ant-design/ant-motion#107]
不使用 `react-router`；
我想使用父组件的state来控制子组件的渲染，同时在子组件 unmount 时触发离场动画；
我看了官网的Demo都是写在一个文件中的；
有没有Demo可以看一下呢？
麻烦了~

**Comment by jljsj33** [comment]
只能用父组件里的 state 来触发离场动画。。。

```jsx
<QueueAnim>
    {this.state.show&& <YouChildren  key="children"/>}
</QueueAnim>
```

**Comment by Feel-Joy** [comment]
@jljsj33 可以实现，谢谢！
不过有个问题就是，这样的话子组件的离场动画是要写在父组件里的，感觉有点奇怪诶。

**Comment by jljsj33** [comment]
不奇怪啊。。。进场出场都在父级标签 `QueueAnim` 上配置，，，子级只管内容即可。。。
