### ISSUE TITLE
landing page 计划

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-motion#109]
- [ ] 不结合编辑工具，增加整套的模板，提供下载；

- [ ] 模板可选择是否 css-modules 样式。

**Comment by afc163** [comment]
将 page builder 独立出来，和 motion 拆开。

**Comment by jljsj33** [comment]
我知道，，网站是要拆开，，但也属于 ant motion 。。。可行？

**Comment by jljsj33** [comment]
看错了，，独立出来放哪去？？？

**Comment by afc163** [comment]
新建仓库。
