### ISSUE TITLE
保存代码出错，请检查saveJsZip

### ISSUE THREAD

**Issue by havefive** [ant-design/ant-motion#11]
Uncaught TypeError: Cannot read property 'split' of null
saveJsZip	@	index.js:69614

**Comment by havefive** [comment]
其它功能选择都不选时，保存会出错。
saveJsZip.jsx133行未验证getURLData('o')为null 的情况
const otherData = getURLData('o').split(',');

**Comment by jljsj33** [comment]
什么浏览器下的？报错截个图

**Comment by jljsj33** [comment]
已解决了，，谢谢

**Comment by jljsj33** [comment]
已解决了，，谢谢
