### ISSUE TITLE
升级reacrt版本之后出现的问题

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-motion#110]
contextTypes was defined as an instance property on TweenOne. Use a static property to define contextTypes instead.

![image](https://user-images.githubusercontent.com/8186664/29318740-ec7724c2-8203-11e7-9f3a-79be336a899a.png)

该怎么解决  回退版本吗?

**Comment by jljsj33** [comment]
tween-one 和 queue-anim 什么版本？？？

**Comment by jljsj33** [comment]
ant motion 里就是 15.6.x 啊，，https://github.com/ant-design/ant-motion/blob/master/package.json#L21

**Comment by baixiaoji** [comment]
报了同样的错误
![image](https://user-images.githubusercontent.com/21168366/29852780-90eeed4e-8d6e-11e7-8ac3-b6089b299f23.png)
![image](https://user-images.githubusercontent.com/21168366/29852783-95847252-8d6e-11e7-9d79-d4a15485756c.png)

**Comment by jljsj33** [comment]
@baixiaoji 报错展开截图上来看看

**Comment by baixiaoji** [comment]
@jljsj33    以解决，谢谢

**Comment by jljsj33** [comment]
@baixiaoji 你怎么解决的，是什么原因出来这问题，能说一下吗？

**Comment by baixiaoji** [comment]
我在页面切换的过程中，只有子元素的时，用了`<QueueAnim />`这个组件包裹，控制台就是有报错上述的错误，后来重看了文档，换成了`<TweenOne />`组件包裹，结果就可以运行了。 @jljsj33  想问问为什么动画组件里面一定要写`key`才能运行，因为前天看到文档中必须写key这句话，昨天有找不到了。

**Comment by jljsj33** [comment]
每个子标签必须带 key，如果未设置 key 将不执行动画。 用 key 是为了记录子级的序列与变更。

**Comment by baixiaoji** [comment]
@jljsj33  和 react 里的 key 是类似的吗？因为 react 里的 key 设置相同也是可以的，但是 motion 里的没有测试过。

**Comment by jljsj33** [comment]
就是 react 的 key, 相同了就不会出现了。。。

**Comment by programmer-yang** [comment]
@jljsj33 
我今天也遇到了这个问题
代码如下：
```
<QueueAnim>
  <Link key="a">page1</Link>
  <Link key="b">page2</Link>
</QueueAnim>
```
解决办法：
```
<QueueAnim>
  <div key="a"><Link>page1</Link></div>
  <div key="b"><Link>page2</Link></div>
</QueueAnim>
```
结论：
初步确认是R4对Link做了一些修改，不能传递key属性进去

**Comment by jljsj33** [comment]
rc-queue-anim v1.2.3
