### ISSUE TITLE
has a contextTypes Error in console

### ISSUE THREAD

**Issue by jwj1648** [ant-design/ant-motion#113]
use ant.design and ant-motion
```html
<Row>
  <TweenOne animation={{ rotate: 180, repeat: -1, duration: 600, repeatDelay: 2000 }} className="close-button">
    <Icon type="close" key='close' />
  </TweenOne>
</Row>
```
there is a warning error in console. like 
```
Warning: contextTypes was defined as an instance property on TweenOne. Use a static property to define contextTypes instead.
```

please, how to fixed it ?

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-motion/issues/110

**Comment by jljsj33** [comment]
`rm -rf node_modules/ && npm install`
Try reinstalling dependencies.

https://codepen.io/jljsj33/pen/bryJKR

**Comment by chenyihao2621023** [comment]
rm -rf node_modules/ && npm install
尝试很多次，但是不起作用，仍然报这个警告
`Warning: contextTypes was defined as an instance property on TweenOne. Use a static property to define contextTypes instead.`

**Comment by jljsj33** [comment]
TweenOne 的版本是什么？？没重现效果，我这边无法判断是什么问题啊。。你看上面的 codepen 的 demo 是没问题啊。。。

**Comment by jljsj33** [comment]
@chenyihao2621023 你的具体操作步骤能贴出来？？

**Comment by chenyihao2621023** [comment]
抱歉 前两天在忙
您demo的例子 也是报同样的警告啊 [http://react-component.github.io/queue-anim/examples/router.html#/page2](url)

**Comment by jljsj33** [comment]
好的，，谢谢，，，是 Route 之类的标签出警告了，，，暂时在 这些标签上层加个 div吧。。

如: 

```jsx
<QueueAnim type={['right', 'left']} className="router-wrap">
          <div key={location.pathname}>
            <Route
              location={location}
              key={location.pathname}
              path="/:url"
              component={component}
            />
          </div>
        </QueueAnim>
```

**Comment by chenyihao2621023** [comment]
好的 解决了！ 谢谢

**Comment by jljsj33** [comment]
rc-queue-anim v1.2.3
