### ISSUE TITLE
生成的代码如何搭建起来

### ISSUE THREAD

**Issue by jamieego** [ant-design/ant-motion#114]
https://motion.ant.design/edit/#t%3Dnav_0_0%2Ccontent_0_0%2Ccontent_2_0%2Ccontent_3_0%2Ccontent_4_0%2Cfooter_0_0

**Comment by jljsj33** [comment]
https://github.com/ant-motion/ant-motion-dva-cli-example

**Comment by jljsj33** [comment]
下载后放到这包的 Home 里

**Comment by jamieego** [comment]
这步会，就是剩下后面的步骤不会了，有详细的教程吗，请问？

**Comment by jamieego** [comment]
这步完成了，剩下的不知道怎样弄起来，能详细点教教我吗？谢谢你

**Comment by jamieego** [comment]
是搭建脚手架，再webpack打包吗？

**Comment by jljsj33** [comment]
发布需要你自个提供空间。。。目前 ant motion 还不支持在线发布。。。
