### ISSUE TITLE
动效模版编辑器的问题

### ISSUE THREAD

**Issue by cnicy** [ant-design/ant-motion#116]
最近后台要做模版开发，无意中发现了这个所见所得的在线编辑器，请问下这个东西是用什么开源的东西做的吗？可以直接拿来用到项目中不？
https://motion.ant.design/edit/#t%3Dnav_0_0%2Ccontent_0_0%2Ccontent_2_0%2Ccontent_3_0%2Ccontent_4_0%2Cfooter_0_0

**Comment by jljsj33** [comment]
你是说这编辑器？？？编辑器的代码全在[这里](https://github.com/ant-design/ant-motion/tree/master/src/edit)啊，，自已写的啊，，是绝静态的一个简单编辑，依靠 url 来做数据储存的。。。

最近也在改这块东西，没服务端还是不告谱，准备改造，目前样式准备可视化全部，刚写了个[编辑样式组件](https://github.com/ant-motion/editor-list)。。

**Comment by cnicy** [comment]
@jljsj33  哎呀，666啊！！改造成啥样啊，什么时候出来，一起来撸怎么样。

**Comment by jljsj33** [comment]
这可能需要点时间，由于我现在也不是专搞这块了，，，可能会久点。。。
目前是想增加个服务端渲和数据库，，，编辑这块没想好倒底怎么整，，如果你有想法，可以一起探讨探讨，，哈哈

**Comment by cnicy** [comment]
可以，后端我可以搞。

**Comment by jljsj33** [comment]
好，，我正缺后端的，，哈哈。。。

**Comment by cnicy** [comment]
@jljsj33 我加你qq了

**Comment by Witee** [comment]
最后的结果是啥？有没有可以用的？
