### ISSUE TITLE
How to use with css modules ?

### ISSUE THREAD

**Issue by yujiayinshi** [ant-design/ant-motion#117]
My project is using css modules，then how can I use ant-motion in my project ?
I try to copy css of ant-motion in my css file， it works for className，but not work for prefixCls。
Could you please give some suggestions ?

**Comment by jljsj33** [comment]
在每个 less 里加上 :global, 详细查看: https://github.com/css-modules/css-modules#usage-with-preprocessors;

**Comment by jljsj33** [comment]
如果是 dva-cli， 还有个方案是在项目根目录建 public 目录，这里的文件会被 copy 到输出目录下，然后在 html 文件里引这个文件。

**Comment by jljsj33** [comment]
更改 webpackConfig.module.loaders
```js
webpackConfig.module.loaders.forEach(function (loader, index) {
     if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.less$') > -1) {
       loader.include = [/node_modules/, /antMotion_style\.less/];
       loader.test = /\.less$/;
     }
     if (loader.test.toString() === '/\\.module\\.less$/') {
       loader.exclude = [/node_modules/, /antMotion_style\.less/];
       loader.test = /\.less$/;
     }
   });
```
