### ISSUE TITLE
首页拼接功能使用反馈

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-motion#12]
1. 选择完成以后，不能返回重新选择（浏览器返回可以，但是无记录）有点麻烦，因为之前选的时候不能预览，只有点了完成才能预览；

2. 我主要用的是生成代码这个功能，代码下下来以后发现配置的地方有两个了（不知是不是必须）感觉最好把每个的配置代码放在各自的组件内部就很好（nav、content、footer等）；

3. nav1，footer1，content3，名字好奇怪呀，还需要自己改名字；

4. 其它还好，有些样式是全局样式，建议在最外层套一层；

**Comment by jljsj33** [comment]
好的，收到了。。。
