### ISSUE TITLE
QueueAnim执行动画的子元素中，绝对定位不能正确显示

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-motion#120]
https://codepen.io/anon/pen/oGwmxG?editors=0010

`import QueueAnim from 'rc-queue-anim';

class Demo extends React.Component {
  state = {
  }
  render() {
    return (
      <div style={{margin:'200px'}}>
          <QueueAnim
            type={'right'}
            delay={30}
            duration={1000}
            ease={'easeInQuart'}
          >
            <div
              key='1'
              >
              <div style={{
                  background:'red',
                  width:'200px',
                  height:'200px',
                  position:'fixed',
                  left:'0',
                  top:'0',
                  zIndex:'10000'
                }}>
           </div>
          </div>
       </QueueAnim>
      </div>
    );
  }
}

ReactDOM.render(<Demo />, mountNode);`

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/issues/3088
