### ISSUE TITLE
dva-cli router4怎么实现路由切换进出动画效果

### ISSUE THREAD

**Issue by laihotin** [ant-design/ant-motion#121]

**Comment by jljsj33** [comment]
性质一样的，，，http://react-component.github.io/queue-anim/examples/router.html#/home

**Comment by laihotin** [comment]
@jljsj33 可是我现在<app><route></app>这样嵌套子路由， react.cloneElement(children, {key: location.pathname})会报错 getAttibute('style')为null

**Comment by jljsj33** [comment]
代码和报错信息贴上来

**Comment by laihotin** [comment]
@jljsj33 

路由是：`<ConnectedRouter history={history}>
      <Layout>
        <Switch>
          <Route path="/" exact render={() => (<Redirect to="/index" />)}/>
          {
            routes.map(({ path, ...dynamics }, key) => (
              <Route
                key={key}
                exact
                path={path}
                component={dynamic({
                  app,
                  ...dynamics
                })}
              />
            ))
          }
        </Switch>
      </Layout>
    </ConnectedRouter>`

在layout是：`<QueueAnim delay={[450, 0]} type={['right', 'left']} appear={false}>
              {hasPermission(locationPathname, permission) ? React.cloneElement(children, {key: locationPathname}) : <Error />}
              </QueueAnim>`

错误信息： `Uncaught TypeError: Cannot read property 'getAttribute' of null
    at eval (webpack-internal:///1055:101:50)
    at Array.forEach (native)
    at Tween.p.setAttrIsStyle (webpack-internal:///1055:90:13)
    at new Tween (webpack-internal:///1055:81:19)
    at TweenOne.start (webpack-internal:///483:252:22)
    at TweenOne.componentDidMount (webpack-internal:///483:79:10)
    at eval (webpack-internal:///663:264:25)
    at measureLifeCyclePerf (webpack-internal:///663:75:12)
    at eval (webpack-internal:///663:263:11)
    at CallbackQueue.notifyAll (webpack-internal:///373:76:22)`

提示是这里getAttribute('style')为null ：
`_this.startDefaultData.style = _this.target.getAttribute('style');`

**Comment by jljsj33** [comment]
```jsx
<Router history={history}>
          <Route render={({ location }) => {
            const to = '/list';
            const key = location.pathname === '/' ? to : location.pathname;
            return (
              <TweenOneGroup
                appear={false}
                enter={{ y: 30, opacity: 0, type: 'from' }}
                leave={{ y: -30, opacity: 0 }}
              >
                <div key={key} id={key}>
                  <Switch location={location}>
                    <Route path="/new" component={New} key="new" />
                    <Route path="/edit" component={Edit} key="edit" />
                    <Route path="/list" component={List} key="list" />
                    <Route path="/result" component={Result} key="result" />
                    <Redirect from="/" exact to={to} />
                  </Switch>
                </div>
              </TweenOneGroup>);
          }} />
        </Router>
```

**Comment by jljsj33** [comment]
Switch 上加 location
