### ISSUE TITLE
nav链接问题

### ISSUE THREAD

**Issue by jamieego** [ant-design/ant-motion#124]
如果要在导航一、二、三加链接，是不是在Nav.jsx模板里添加？还是用别的什么方式。

**Comment by jljsj33** [comment]
https://ant.design/components/menu-cn/#components-menu-demo-horizontal

**Comment by jamieego** [comment]
添加“分屏锚点”这个组件，会渲染不出来呢！ @jljsj33

**Comment by jljsj33** [comment]
？？？什么情况下渲染不出来？？？说下你的使用场景与操作步骤吧。。。

**Comment by jamieego** [comment]
https://motion.ant.design/edit/#t%3Dnav_0_0%2Ccontent_0_0%2Ccontent_2_0%2Ccontent_3_0%2Ccontent_4_0%2Cfooter_0_0

Home中的index调用了point整个页面都无法加载；不调用point组件，页面就渲染的出来。

**Comment by jljsj33** [comment]
把你生产的代码的短链接给我，，我明天看看。。 @520Yanxiaofei
