### ISSUE TITLE
FLIP animation

### ISSUE THREAD

**Issue by mehwww** [ant-design/ant-motion#126]
Does ant-motion support [FLIP](https://aerotwist.com/blog/flip-your-animations/) animation?

**Comment by jljsj33** [comment]
？？？？？？？？

**Comment by jljsj33** [comment]
翻转动画？

**Comment by mehwww** [comment]
就是先计算出终点的位置再算出位移然后加 transform 和 transition 形成一种平滑的位移效果，比如这个 http://joshwcomeau.github.io/react-flip-move/examples/#/shuffle

**Comment by jljsj33** [comment]
现在的处理方式就是这样啊，，只要我们用的是 tween-one 为底层做动画。。。

**Comment by MrHeer** [comment]
@jljsj33 我好像没有看到 FLIP 的相关源码。
@mehwww 解释的不太详细，FLIP 核心是

1. First: 记录初始状态（位置，宽高，等等）
2. Last: 在元素发生变化后，记录最后的终点位位置，这个时候应该调用 `getBoundingClientRect()` 去强制同步布局
3. Invert: 计算 diff = First - Last.
4. Play: 这个时候元素其实已经在终点位置了，并且浏览器页完成布局了，后面的动画是因为通过 transform(diff) => transform(0) 这个过程。

综上所述：FLIP 让浏览器来计算终点状态，通过 Invert 中计算的 diff 在布局完之后来 play 而已。这样可以减少浏览器布局的性能消耗。而且通过浏览器来告诉我元素最后的状态。

**Comment by jljsj33** [comment]
tween-one 就是这样的。。。汗，，如果你要用 transition 或 animation 可以用 rc-motion 或 rc-animate。。。

TweenOne 是不会重新布局的，依赖 requestAnimationFrame 是每帧计算的，animation 或 transition 里帮你计算了

queue-anim 是需要触发布局的，，组件里面管理渲染的元素的。。

**Comment by MrHeer** [comment]
这里的关键不是重新布局，这里的关键是我可能并不知道这个元素的最后会在什么位置，是通过浏览器的渲染机制，通过`getBoundingClientRect()`来自动获取元素的位置的。我知道`TweenOne`不会重新布局，但是它好像需要我给它提供一个终点状态吧？可能是我没看懂源码，后面再研究研究

**Comment by MrHeer** [comment]
@jljsj33 我看了 `TweenOne`, 我确实确实没有看到 `FLIP` 思想的体现，没有核心步骤 `Invert`。我看到的是，您通过用户拿到了终点位置，然后你全程控制的如何将元素驱动到终点位置。不知道是否我理解有误。

**Comment by jljsj33** [comment]
requestAnimationFrame 是每帧计算的， 如果你要用 transition 或 animation 可以用 rc-motion 或 rc-animate，，

**Comment by jljsj33** [comment]
两个维度的东西。。一个依赖 requestAnimationFrame, 一个依赖transition，，虽然过程不一样，，但最终的效果是一样的。。animation 或 transition 里帮你计算了

**Comment by MrHeer** [comment]
Play 的阶段你可以用任何方式去 play, 你可以 requestAnimationFrame， transition， 等等其他 API。我的意思是我没在代码里看到 Invert 的阶段。

**Comment by jljsj33** [comment]
type="from"

**Comment by jljsj33** [comment]
`<TweenOne animation={{ x: 100 }} type="from" />` 
元素从100像素到当前位置，，你说的是不是这个意思？？

**Comment by MrHeer** [comment]
也不是，FLIP 的思想挺有意思的，特别是用来实现布局动画。比如 Gird 布局，我不需要设置任何动画参数，我只需要随机打乱顺序，就会自动计算 Diff 来产生动画。我在打乱的时候，动画库会记录每个元素的位置，然后记录打乱后每个元素的位置。这样我就可以拿到那个状态的 Diff，从而产生动画。也就是你这里的 from，应该通过 Invert 自己计算，而不是用户来计算。

**Comment by MrHeer** [comment]
@jljsj33 这里有个 Demo，使用者不需要告诉组件具体的位置(从哪儿来，到哪儿去)。我只需要告诉他我的顺序变了你就应该自己运动到该去的位置。其实在打乱后就已经在最后的位置了，只不过在渲染第一帧的时候通过 Invert 把元素 transform 到之前的位置。这样可以防止重新布局。
https://codesandbox.io/s/14v8o5xy44

**Comment by jljsj33** [comment]
好吧，不一样的东西，脑回路没转过来，这层确实不是动画库所要做的事，，功能性这个现在只有 queue-anim，，还是需要自已写，，，后续可以看有必要可以合到 queue-anim 里，

**Comment by MrHeer** [comment]
哈哈，他这个确实有点巧妙，我也看了好几遍才明白作者的意思。也谢谢你耐心听我唠叨半天

**Comment by jljsj33** [comment]
其实也是简单的，，记录一下就可以实现,, https://codesandbox.io/s/epic-gauss-botv9?file=/src/App.js

**Comment by jljsj33** [comment]
后续可以加到 queue-anim 里。。。

**Comment by MrHeer** [comment]
是的，实现起来不难，我是觉得思想很巧妙。
