### ISSUE TITLE
BannerAnim定时器叠加问题

### ISSUE THREAD

**Issue by 1335382915** [ant-design/ant-motion#127]
当前需求：商品详情页顶部轮播图，点击图片后打开弹出框查看大图（弹出框同样使用BannerAnim）。如果详情页和查看大图之间反复切换（rerender），则轮播图速度越来越快。

**Comment by jljsj33** [comment]
ant design 的弹出框？？ 有没有重现: https://codepen.io/jljsj33/pen/WOQdjB
