### ISSUE TITLE
与bootstrap modal配合的bug

### ISSUE THREAD

**Issue by YDJSZY** [ant-design/ant-motion#129]
![image](https://user-images.githubusercontent.com/14819143/31760697-2a804100-b47b-11e7-80a7-880b1ebd6465.png)
![image](https://user-images.githubusercontent.com/14819143/31760747-51c7a8ac-b47b-11e7-929f-d2ba11e93467.png)

如上图。如果我把下面这个transform去掉就正常。
![image](https://user-images.githubusercontent.com/14819143/31760799-80ecabb4-b47b-11e7-9530-d19ec4e81338.png)

**Comment by jljsj33** [comment]
动画过程没问题的话，，增加个结束回调把 transform 设回 none;

https://github.com/ant-design/ant-design/issues/3088

**Comment by YDJSZY** [comment]
嗯。可以了。onEnd回调把 transform 设回 none。谢谢！！！
