### ISSUE TITLE
server problem

### ISSUE THREAD

**Issue by aLIEzsss4** [ant-design/ant-motion#135]
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client)  data-reactid="53"></div></div><div clas
 (server)  data-reactid="53"><div style="display:b

**Comment by aLIEzsss4** [comment]
使用的react starter kit 脚手架

**Comment by jljsj33** [comment]
展开截下图看看。。

**Comment by jljsj33** [comment]
没反应，先关闭
