### ISSUE TITLE
首页制作工具

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-motion#136]
其实现在的 [动效模板](https://motion.ant.design/edit/#t%3Dnav_0_0%2Ccontent_0_0%2Ccontent_2_0%2Ccontent_3_0%2Ccontent_4_0%2Cfooter_0_0) 已经很强大了，但是类型还是太过于单一，我觉得可以结合之前 DesignX(手动打码) 的一些技术搞一个首页制作器，像 `pro`，`antd` 这些站点的首页直接搭建就好了，根本不需要写代码。

@jljsj33 你之前也搞过 DesignX ，怎么看...

**Comment by jljsj33** [comment]
我也想啊，，看我 ant motion 的 2 期想做的事啊，一个就是现成整套的模板 landing page 提供下载，一个就是想整你说的那 xxxx ，，还想搞一键生成 build 后的 html 代码一键发布啊，，可谁来搞后端啊，，，我觉得你可以。。。你去把 xxx 的后端的拉过来。。。我们一起来搞。。。咋样？？？

**Comment by nikogu** [comment]
@jljsj33 我可以搞后端呀，不过我们现在系统的后端搞对外的比较麻烦，对内的基础技术倒是很成熟

**Comment by jljsj33** [comment]
明天找你聊聊
