### ISSUE TITLE
如何引入本地图片

### ISSUE THREAD

**Issue by jamieego** [ant-design/ant-motion#137]
<img width="100%" src="https://os.alipayobjects.com/rmsportal/mlcYmsRilwraoAe.svg" />
img width="100%" src="https://os.alipayobjects.com/rmsportal/mlcYmsRilwraoAe.svg" /
Home文件夹中nav.jsx的logo属性是上面那样的
<img width="100%" src="./img/logo.jpg" />
img width="100%" src="./img/logo.jpg" /
改了本地图片后就显示不出来，这样添加本地图片是错误的吗？
请问怎么解决，O(∩_∩)O谢谢 @jljsj33

**Comment by jljsj33** [comment]
试试 
```jsx
cont img = require('./img/logo.jpg);

<a src={img} />
`

**Comment by jamieego** [comment]
好的👌，谢谢辣
