### ISSUE TITLE
模块跳转

### ISSUE THREAD

**Issue by jamieego** [ant-design/ant-motion#144]
如何在首页点击“第二页”跳转到“另外一个模块”
Nav和Footer模块不变，改变content模块
望详细点，谢谢你喔

const navData = { menu1: '首页', menu2: '第二页', menu3: '第三页'};;
    const linkData = { menu1: '#',menu2: '#',menu3: '#'};;
    const navChildren = Object.keys(navData)
      .map((key, i) => (<Item key={i}><a href={linkData[key]}></a>{navData[key]}</Item>));

**Comment by jljsj33** [comment]
这恐怕一两名说不清楚。。。先去学习 [react-router](http://react-guide.github.io/react-router-cn/docs/API.html)。。。
