### ISSUE TITLE
请问，支持ie吗

### ISSUE THREAD

**Issue by chenyihao2621023** [ant-design/ant-motion#147]
我刚试了下 ie10浏览器打不开网页 报`SCRIPT1002: 语法错误`。
想请问下，支持ie吗，如果支持，支持到ie几呢？

**Comment by jljsj33** [comment]
打开什么报错？

**Comment by chenyihao2621023** [comment]
ie 10没问题了；
ie 9下 `SCRIPT5022: matchMedia not present, legacy browsers require a polyfill`  应该是matchMedia 这个组件需要polyfill
ie 8下 `SCRIPT1028: 缺少标识符、字符串或数字`,断点在这里`function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`
查了下，说是ie将delete default 当做保留字，可是我还没找到解决办法

**Comment by jljsj33** [comment]
https://ant.design/docs/react/getting-started-cn#%E5%85%BC%E5%AE%B9%E6%80%A7
看下这个。。。

**Comment by chenyihao2621023** [comment]
看过了
说是需要es3ify-loader
`
{
                test: /.jsx?$/,
                enforce: 'post',
                loader: 'es3ify-loader',
                exclude: /node_modules/
            }
`
我是这么配的,bundle.js文件生效，但是 在vendor.js中 `function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }` 没有改过来
请问下，我webpack这么写有问题吗， es3ify-loader 需要配exclude吗,如果不配置 ant的包会报如下错误
`Module build failed: Error: Parse Error: Line 1: Illegal import declaration`

**Comment by jljsj33** [comment]
你具体怎么配置的，，如果两个都用了，你看下这个 issues
![image](https://user-images.githubusercontent.com/6802825/34241945-c8ce700c-e653-11e7-814c-f2eb05d30f43.png)

**Comment by chenyihao2621023** [comment]
只在入口文件 main.js 中 引入了 babel-polyfill 
这是我的项目地址  [https://github.com/chenyihao2621023/nextTalkHouse](url)
脚手架是根据 vue-cli改的  loader配置在 `webpack.prod.conf.js`
可以耽误您一些时间， 麻烦帮我看一下吗？谢谢...

**Comment by jljsj33** [comment]
vue-cli ？？？醉了。。。。

**Comment by chenyihao2621023** [comment]
是根据vue-cli改的

**Comment by jljsj33** [comment]
汗，自个改的脚手架自个处理。。。找死我了。。。。

你的 dev-client.js 里的代码语法错误， ，，你自个看下。。。

**Comment by jljsj33** [comment]
![image](https://user-images.githubusercontent.com/6802825/34247096-4d4c9152-e66c-11e7-9e0e-fece38beac5d.png)

dev.conf.js 里把 babel-polyfill 放后面去了。。。


![image](https://user-images.githubusercontent.com/6802825/34247110-57df32b4-e66c-11e7-9910-50a13db01efb.png)

**Comment by jljsj33** [comment]
```
const hotClient = require('webpack-hot-middleware/client?noInfo=true&reload=true');
```
这个报错

**Comment by chenyihao2621023** [comment]
作为伸手党的我，深深觉得可耻。那啥，大佬，需要先`npm run build`一下，然后 `node prod.server.js `。
我自己搞，自己搞，谢谢大佬。你说你在杭州，要是在北京，我肯定请你喝咖啡。再次感谢！

**Comment by afc163** [comment]
大概率是 vue-cli 的问题，你这样没解决调试时报错的问题，建议到 vue-cli 那里去寻找解决方案。

**Comment by jljsj33** [comment]
不是 vue-cli 的问题，，是 ie 下不支持 `webpack-hot-middleware/client?noInfo=true&reload=true` 这样。。。加 `eventsource-polyfill` 也没用，，就是不支持这种写法。。。

**Comment by chenyihao2621023** [comment]
调试的话，我可以先忍了。build出来，ie8报错，还在找原因。谢谢两位大佬。回头我投简历，面试当面么么哒你们。赶紧歇会

**Comment by jljsj33** [comment]
是dev-clinet 没包在支持 require 的里面，，你把 dev-clinet 里的放到 main.js 里就可以了。。。

**Comment by chenyihao2621023** [comment]
放到main.js里？是下面这样吗。。。
`// main.js`
`
require('eventsource-polyfill');
`
`
const hotClient = require('webpack-hot-middleware/client?noInfo=true&reload=true');
`
`
hotClient.subscribe((event) => {
    if (event.action === 'reload') {
        window.location.reload();
    }
});
`
`
ReactDOM.render(
  <App />
, document.getElementById('app'));
`

**Comment by jljsj33** [comment]
是啊...

**Comment by chenyihao2621023** [comment]
谢谢谢谢谢谢，有没有请大佬喝咖啡的地址。。。

**Comment by jljsj33** [comment]
😓 。。。不用了，，能解决问题就行了。。。
