### ISSUE TITLE
ant-design官方文档中的theme实时更换

### ISSUE THREAD

**Issue by chenyihao2621023** [ant-design/ant-motion#149]
刚用到了ant-design，可是看换肤的文档都是通过webpack定义` modifyVars` 来覆盖原来的样式变量。
但是，官网是可以实时换肤的。clone了一份代码
 `
window.less.modifyVars({
        '@primary-color': color,
      }).then(() => {
        message.success(messages['app.footer.primary-color-changed']);
        this.setState({ color });
      });
`
不明白`window.less.modifyVars`这个方法到底是哪来的。。。

**Comment by chenyihao2621023** [comment]
`// ant-design项目  Footer.jsx p:38`
![123](https://user-images.githubusercontent.com/21965525/34660554-33115eba-f47e-11e7-93c1-03430be27c0c.png)

**Comment by jljsj33** [comment]
http://lesscss.org/usage/#using-less-in-the-browser-modify-variables

**Comment by chenyihao2621023** [comment]
按你的提示，window.less已经有值了
下面是我的代码
```js
// webpack.config.js
{
     test: /\.less/, 
     use: [
       {
           loader: "style-loader"
       },
       {
          loader: "css-loader"
       },
       {
          loader: "less-loader",
             options: {
                "modifyVars":{ "primary-color": "#1DA57A",  }
           }
       }
     ]
},
```
```js 
  // main.js
window.less.modifyVars({
    '@primary-color':  '#e4393c'
 }) 
```
```less
  // app.less
 @import "~antd/dist/antd.less"; 
```
但是依然没效果，是哪里的问题呢。。。

**Comment by yesmeck** [comment]
官网的事实跟换不是通过  webpack 实现的。而是在浏览器端编译  less 实现的，具体实现可以自己看代码。关键代码：

https://github.com/ant-design/ant-design/blob/master/site/theme/template/Layout/Footer.jsx#L35-L59

https://github.com/ant-design/ant-design/blob/master/site/theme/static/template.html#L63

https://github.com/ant-design/ant-design/blob/master/scripts/generateColorLess.js

**Comment by chenyihao2621023** [comment]
```js 
// generateColorLess.js
const styles = glob.sync(path.join(antd, 'components/*/style/index.less'));
```
这段代码我也要放一个components文件夹去供他读取吗
```js 
 // package.json
 "start": "rimraf _site && node ./scripts/generateColorLess.js && cross-env NODE_ENV=development bisheng start -c ./site/bisheng.config.js",
```
还有package.json 这些 也是需要改的吧
想问下，有预制主题 生成index.css的方法么,比如 element-ui[https://elementui.github.io/theme-chalk-preview/#/zh-CN](url)
然后我可以通过在页面获取css，动态生成style标签,并且操作该style标签的样式来达到实时换肤

**Comment by EugeneHuang95** [comment]
@yesmeck 
in the [generateColorLess.js](https://github.com/ant-design/ant-design/blob/master/scripts/generateColorLess.js)：
```javascript
const reducePlugin = postcss.plugin('reducePlugin', () => {
  //....
}
```
Whats the usage of this plugin? I cannot understand it. Thanks.

**Comment by yesmeck** [comment]
Extract color related style rules.

**Comment by EugeneHuang95** [comment]
So It seems only work for the variable of primary-color?  I've just tried other variable but it doesnt work.

**Comment by EugeneHuang95** [comment]
@yesmeck 
So It seems only work for the variable of primary-color? I've just tried other variable but it doesnt work.

**Comment by v5zz** [comment]
![image](https://user-images.githubusercontent.com/47095302/51812492-b709a680-22ec-11e9-9b17-7f7bb62679db.png)
I met this problem

**Comment by v5zz** [comment]
有没有配置成功的

**Comment by v5zz** [comment]
![image](https://user-images.githubusercontent.com/47095302/51896909-7000db80-23e8-11e9-8adc-ea301e610d23.png)
root是在哪里配置的
