### ISSUE TITLE
ant motion 

### ISSUE THREAD

**Issue by CloudIsNoCloud** [ant-design/ant-motion#151]
为什么那个模板页会打不开啊。
[https://motion.ant.design/edit/#t%3Dnav_0_0%2Ccontent_0_0%2Ccontent_2_0%2Ccontent_3_0%2Ccontent_4_0%2Cfooter_0_0](https://motion.ant.design/edit/#t%3Dnav_0_0%2Ccontent_0_0%2Ccontent_2_0%2Ccontent_3_0%2Ccontent_4_0%2Cfooter_0_0)

**Comment by jljsj33** [comment]
Thx
