### ISSUE TITLE
下载模板加载less错误

### ISSUE THREAD

**Issue by 13618396691** [ant-design/ant-motion#155]
@import "~antd/lib/style/themes/default.less";

./src/style/index.less
Module build failed: 

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in /Users/mac/work/singularity/sigly/node_modules/antd/lib/style/color/bezierEasing.less (line 110, column 0)

**Comment by yesmeck** [comment]
参考 https://github.com/ant-design/ant-design/issues/7927#issuecomment-372513256

**Comment by agarwal00s** [comment]
@yesmeck 
const path = require('path');

let disableDynamicImport = false;
let hostUrl = 'https://app.yellowmessenger.com';
if (process.env.NODE_ENV && process.env.NODE_ENV.toLowerCase() === 'development') {
  disableDynamicImport = true;
  hostUrl = 'https://staging.yellowmessenger.com';
}
export default {
  entry: 'src/index.js',
  extraBabelPlugins: [['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }]],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
  },
  alias: {
    "@babel/runtime": path.resolve(__dirname,"node_modules/@babel/runtime"),
     components: path.resolve(__dirname, 'src/components/'),
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs',
  },
  disableDynamicImport,
  publicPath: '/',
  hash: true,
  define: {
    CDN_URL: process.env.CDN_URL || 'https://cdn.yellowmessenger.com',
    HOST_URL: process.env.HOST_URL || hostUrl,
    XMPP_DOMAIN: process.env.XMPP_URL || 'xmpp.yellowmssngr.com',
    INSIGHTS_STORAGE: process.env.INSIGHTS_STORAGE
  }
};

Where to add that config ?

**Comment by agarwal00s** [comment]
@yesmeck 

.webpackrc.js
const path = require('path');

let disableDynamicImport = false;
let hostUrl = '';
if (process.env.NODE_ENV && process.env.NODE_ENV.toLowerCase() === 'development') {
  disableDynamicImport = true;
  hostUrl = '';
}
export default {
  entry: 'src/index.js',
  extraBabelPlugins: [['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }]],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
  },
  alias: {
    "@babel/runtime": path.resolve(__dirname,"node_modules/@babel/runtime"),
     components: path.resolve(__dirname, 'src/components/'),
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs',
  },
  disableDynamicImport,
  publicPath: '/',
  hash: true,
  define: {
    CDN_URL: process.env.CDN_URL || '',
    HOST_URL: process.env.HOST_URL || hostUrl,
    XMPP_DOMAIN: process.env.XMPP_URL || '',
    INSIGHTS_STORAGE: process.env.INSIGHTS_STORAGE
  }
};

where to add that configuration ?
