### ISSUE TITLE
Ant Motion中列表交换会使右侧进度条消失，形成抖动，不知会不会对项目造成影响

### ISSUE THREAD

**Issue by JokerLoLgrey** [ant-design/ant-motion#158]
Ant Motion中列表交换会使右侧进度条消失，形成抖动，不知会不会对项目造成影响
![default](https://user-images.githubusercontent.com/33446705/38713126-34278ca6-3f02-11e8-9cf2-9ba49cb27631.png)
![default](https://user-images.githubusercontent.com/33446705/38713129-3811192c-3f02-11e8-8c6b-9c81aec092ba.png)

**Comment by jljsj33** [comment]
拖动时目前是把页面的滚动干掉的吧，避免页面滚动导至错位。如果你有好的方案可以 PR.
