### ISSUE TITLE
动效模版“单张背景图Banner2”切换到手机版样式的时候渲染失败

### ISSUE THREAD

**Issue by xyzard** [ant-design/ant-motion#159]
https://motion.ant.design/templates/#t%3Dcontent_10_0

具体是这个连接上面的模版。电脑打开后瞬速地缩小页面到768px以下的时候渲染失败，刷新页面重复操作一直是渲染失败

提示：TypeError: Cannot read property 'width' of undefined

**Comment by jljsj33** [comment]
这种切换不应该出现在正常操作里，是 QueueAnim 没完成导至，不影响正常运行，，谢谢反馈。
