### ISSUE TITLE
【样式问题】关于BannerAnimBanner动画Arrow组件

### ISSUE THREAD

**Issue by wucipo** [ant-design/ant-motion#163]
## 问题叙述
Arrow组件会自动计算top的值，并写入到行内样式中！！
## 目的
样式都由自身class名控制或者自身写入top值决定！！！

### 图片栗子
![qq 20180519121801](https://user-images.githubusercontent.com/18008712/40264808-c324e78c-5b5e-11e8-80c2-b8e5cde692c4.png)
![qq 20180519121829](https://user-images.githubusercontent.com/18008712/40264807-c2d96136-5b5e-11e8-8690-222d6e2029bf.png)
![qq 20180519121930](https://user-images.githubusercontent.com/18008712/40264818-f1bb3ccc-5b5e-11e8-8fe0-3022b773f241.png)

**Comment by jljsj33** [comment]
!important
