### ISSUE TITLE
Link跳转问题

### ISSUE THREAD

**Issue by LinSundy** [ant-design/ant-motion#164]
使用了ant-motion, 首页web/index    Nav使用了ScrollAnim.Link, 实现了屏幕切换。 但内页 '案例' web/case 的Nav 使用的是react-router-dom里的Link，  我想实现从web/case 跳转到 web/index 里的 ‘关于’ 一屏       ( 就是 ‘首页’ 跟 ‘案例’是2个页面, 从其他页面跳转到首页的某一屏) 如何跳转呢？ 大佬
![image](https://user-images.githubusercontent.com/13688052/41029742-154725c6-69af-11e8-8cfe-878a8d512c39.png)

**Comment by jljsj33** [comment]
web/index#xxx(首屏的 id) 不行?

**Comment by LinSundy** [comment]
@jljsj33 找到原因了。。 是this.state.show  影响的。  如果index.js  render 只{children} 是可以的， 一直没明白这个show的作用

**Comment by jljsj33** [comment]
这个 show 是为了解决开发环境里 css 实时 build，在标签里加载，导至第一次进来没有 build 出样式，banner 组件的高度获取不了，就会出错。。。如果不是  dva 或 umi ，，，你可以直接删除。。
