### ISSUE TITLE
overPack在子组件中如何使用？ 

### ISSUE THREAD

**Issue by whateveryoudo** [ant-design/ant-motion#166]
react中,overPack包裹的不一定是本身的 Tween 或者 QueueAnim ,可能是我们自己定义的组件,这时候发现子组件不会滚动显示的效果,请问下 如何实现呢？(试验过加载父级同层,会把子组件当成一个整体)

**Comment by jljsj33** [comment]
overPack 的子组件须是 tween-one 或 queue-anim 之类的以切换子级来做动画效果的组件, 如 rc-animate 也是支持的。。如果你的组件没这个功能，，那请在你的组件上面套一个 queue-anim 就可以了。。。
```jsx
<OverPack>
  <QueueAnim component="" key="queue">
      <YouComponent  key="queue-1"/>
  </QueueAnim>
<OverPack>
```

**Comment by jljsj33** [comment]
Row 的动画可以这么写

```jsx
<QueueAnim
  key="ul"
  className={styles.cons_lists}
  type="bottom"
  component={Row}
>
 {children} // children 里带 key
</QueueAnim>
```

**Comment by whateveryoudo** [comment]
那么这样怎么组件化呢？》比如 我的header很多地方都会用的？

**Comment by whateveryoudo** [comment]
row那个我知道,我是为了栅格布局,但是还是我最开始提出的问题,有什么解决办法呢？

**Comment by whateveryoudo** [comment]
我看了文档,component参数是不支持reactNode的啊  只是string,我之前页试过,这样的话我的ContentHeader就可以写成component={ContentHeader} 也不会有这个问题了。。。

**Comment by jljsj33** [comment]
做成组件的话，真没办法控制你组件里的子级的出场，要不你加个参数去控制，然后在组件里切换。。。
```jsx
<OverPack 
  onChange={(e) => {
    this.setState({ show: e.mode === 'enter' });
  }}
>
  <TweenOne animation={{ delay: 1000, duration: 0 }} component={ContentHeader} componentProps={{ show: this.state.show }}/>
</OverPack>
```

**Comment by whateveryoudo** [comment]
我试试看,谢啦

**Comment by whateveryoudo** [comment]
我之前说错了,是能够使用reactNode，我没用对。。我写成了{<xx></xx>},基础知识没掌握好。。
