### ISSUE TITLE
List Sort doesn't draggable

### ISSUE THREAD

**Issue by sahar922** [ant-design/ant-motion#168]
Hi all,
I copied the same code as the demo [here](https://motion.ant.design/exhibition/demo/list-sort) shows.
The list and the CSS design is working well, but none of the list items are draggable.

when I click on an item, he became bigger but do not move at all, as shown in the picture below.
![screen shot 2018-06-20 at 5 21 18 pm](https://user-images.githubusercontent.com/12861093/41664449-6e2ffa96-74ae-11e8-81e6-9a065cba6ecf.png)

what am I missing?

Thanks!

**Comment by jljsj33** [comment]
please provide your demo, https://42vvz4j4yx.codesandbox.io/

**Comment by jljsj33** [comment]
https://codesandbox.io/s/n1p6k7n440. no problem.
