### ISSUE TITLE
你好 未能正确反映translate和rotate先后顺序

### ISSUE THREAD

**Issue by mjc224000** [ant-design/ant-motion#169]
rc-tween-one@2.0.7   
{rotateX: 0, rotate: 0, rotateY: 0, duration: 200},
            {x: singularX + centerX, y: singularY + centerY},
            {rotateX: x / column * 360, rotateY: y / row * 360,},
            {translateZ:-800,delay:1000}

先rotate再translateZ这个顺序很重要，但是渲染在页为 translate3d(600px, 200px, -457px) rotateY(60deg)
先translate再rotate

**Comment by mjc224000** [comment]
Hello failed to correctly reflect the order of translate and rotate
   {rotateX: 0, rotate: 0, rotateY: 0, duration: 200},
            {x: singularX + centerX, y: singularY + centerY},
            {rotateX: x / column * 360, rotateY: y / row * 360,},
            {translateZ:-800,delay:1000}

Rotate then translateZ this order is very important, but the rendering on page is translate3d(600px, 200px, -457px) rotateY(60deg)
First translate and then rotate

**Comment by mjc224000** [comment]
397938635@qq.com

**Comment by mjc224000** [comment]
期望的渲染结果
![image](http://www.mjc224000.top/wp-content/imgs/qiwang.png)

**Comment by mjc224000** [comment]
expected render code in html
![image](http://www.mjc224000.top/wp-content/imgs/qiwangcode.png)

**Comment by mjc224000** [comment]
but reality is 
![image](http://www.mjc224000.top/wp-content/imgs/xianshi.png);

**Comment by mjc224000** [comment]
because you render translate prop first,
i will get fired

**Comment by mjc224000** [comment]
![](http://www.mjc224000.top/wp-content/imgs/code.png)
here is my code ,dose it look like write translate prop first?

**Comment by jljsj33** [comment]
刚看到。。。

**Comment by jljsj33** [comment]
有什么问题？？？？你的 demo 地址呢？

**Comment by jljsj33** [comment]
这顺序正常来说 translate 就应该在 rotate 前面。。。如果在影响到效果，，可以考虑下再套一层，，，一层管旋转，一层管位移。。。
