### ISSUE TITLE
如何实现单一窗口滚动

### ISSUE THREAD

**Issue by sjcUD** [ant-design/ant-motion#170]
我想实现这样的效果，请问ScrollAnim如何控制翻页的时候下个页面就是一个窗口，而不是随着滚动条滚动
![default](https://user-images.githubusercontent.com/24570594/41756285-645cd708-760e-11e8-8ae1-49526c8c0669.gif)

**Comment by jljsj33** [comment]
暂时还没这样的组件，后续会考虑。。目前 slides 的形式可以用 banner-anim 加自已监听滚动来完成。。。

**Comment by sjcUD** [comment]
多谢回复，期待后续加上，非常棒的项目

**Comment by sjcUD** [comment]
@jljsj33

**Comment by DuduStyle** [comment]
这个目前还没有计划开始实行嘛

**Comment by jljsj33** [comment]
没有，，如果你有兴趣，可以 pr。。。。
