### ISSUE TITLE
新模块

### ISSUE THREAD

**Issue by oqq5518** [ant-design/ant-motion#18]
新模块大概什么时候能开放呢？

**Comment by jljsj33** [comment]
这块可能还需要点时间。。。。

**Comment by zaxlct** [comment]
期待！！！！

**Comment by oqq5518** [comment]
自由搭配页面的功能有问题，你全选功能模块，自动生成代码，页面会一直加载..

**Comment by jljsj33** [comment]
@oqq5518 可以新起个 issuse；

这块是 banner-anim link改了，所以报错，，由于我这边在改版，所以没更新，如果你现在紧需使用，，可以不勾选侧边小点，然后依照最新的banner-anim API 自行添加这小点。。。

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-motion/issues/29

**Comment by oqq5518** [comment]
那什么时候能发新版呢？

**Comment by jljsj33** [comment]
下月月底差不多。。。

我把那个bug修复下吧。。。

**Comment by oqq5518** [comment]
谢谢 正想用呢
