### ISSUE TITLE
index.js:2178 Warning: React does not recognize the `computedMatch` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `computedmatch` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by zjscy666** [ant-design/ant-motion#185]
this is my homepage routes , not contains login page  and 404 page, I use like this to get my homepage routes,it can work ,but  has a warning
this is my codes 
![image](https://user-images.githubusercontent.com/22449281/44148166-b05c14d0-a0c9-11e8-9308-71aac86cc44f.png)
this is  warnings 
![image](https://user-images.githubusercontent.com/22449281/44148180-c3a6a46a-a0c9-11e8-8184-608194dde57f.png)
I must use Switch,how I can do it,thanks!

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-motion/issues/121

**Comment by zjscy666** [comment]
我看了#121 但是不行 我直接放更元素就可以了 但是还有个问题 我和react-loadable连用 好像会冲突

**Comment by jljsj33** [comment]
please provide your demo, https://codesandbox.io/s/42vvz4j4yx

**Comment by lasantha57** [comment]
The solution is simple, just add another layer of `<React.Fragment>` after `<Switch>`. Hope it helps.

**Comment by mcmwhfy** [comment]
> The solution is simple, just add another layer of `<React.Fragment>` after `<Switch>`. Hope it helps.

but what is the deal having a "blind element" in between ?

**Comment by neenus** [comment]
> The solution is simple, just add another layer of `<React.Fragment>` after `<Switch>`. Hope it helps.

This worked thank you! but curios to know why its necessary though?

**Comment by aifeelit** [comment]
In this case, the child is your <div></div>, so a non standard props computedMatch are being passed to native dom node <div>, thus React gives you an healthy warning. So, using <> or <Fragment> will discard the warning.
