### ISSUE TITLE
请问如何配合ant-design的表格组件，实现增删改效果呢？

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-motion#19]
现有的文档基本上是针对单个组件的，请问如何配合ant-design的表格组件，实现增删改效果呢？

比如新增一行，渐进，删除一行渐出，更新一行给予提示？ 

前段大菜鸟提问。 谢谢。

**Comment by jljsj33** [comment]
表格里有的。。。。

**Comment by jljsj33** [comment]
http://react-component.github.io/table/examples/animation.html

**Comment by xjdata** [comment]
不好意思。 以后除了官方给出的说明文档，以后会多找一步，如果组件是基于某个组件的基础上弄的，那就在搜一下那个组件的文档。 额。。。不好意思了。

谢谢你。

**Comment by jljsj33** [comment]
额，，antd 上 demo 没有啊。。。。

**Comment by afc163** [comment]
ant-motion 可以提供这些例子。

**Comment by xjdata** [comment]
嗯， 确实没找到。 我看issues里 已经有人在讨论table的增删改，但是貌似大家都没好的实现。 我需求一样的，就是希望table中的增删改操作能符合 https://ant.design/docs/spec/transition#解释刚刚发生了什么。要是table组件能够提供最基础的一些动效开关就好了。后台系统中没那么花哨的要求，就是希望能做到提醒用户。额。。。。当然这是非分之想。依然感谢antd/dva

**Comment by afc163** [comment]
嗯，https://ant.design/docs/spec/transition 可以加个链接到 motion 这边来。

**Comment by jljsj33** [comment]
我加个
