### ISSUE TITLE
Uncaught (in promise) Error: Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by lei14370** [ant-design/ant-motion#190]
![image](https://user-images.githubusercontent.com/24383279/47071844-2d473900-d227-11e8-9cc1-5961b591b1e2.png)
直接复制的模板 一个都不得行

**Comment by jljsj33** [comment]
什么脚手架？？？TweenOne 里取 dom 报错。。。贴一下你的环境和脚手架吧。。。

**Comment by jljsj33** [comment]
或者把 html 上外链的 cdn 的react删了。。
