### ISSUE TITLE
The official demo cannot be restored

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-motion#191]
[![Edit r448j880y4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r448j880y4)

origin link adds : https://motion.ant.design/exhibition/demo/table-enter-leave

**Comment by jljsj33** [comment]
....

通用样式
https://github.com/ant-design/ant-motion/blob/master/src/theme/static/global.less

antd 样式
import 'antd/dist/antd.css';


[![Edit 13lojpmxnj](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/13lojpmxnj)

**Comment by tolerance-go** [comment]
emm...  https://motion.ant.design/exhibition/demo/table-enter-leave It's animated！
