### ISSUE TITLE
BannerAnim onChange 为什么要回调两次呢..感觉有点多余

### ISSUE THREAD

**Issue by abc879475908** [ant-design/ant-motion#192]
BannerAnim onChange 为什么要回调两次呢..感觉有点多余

**Comment by jljsj33** [comment]
一个是切换动画开始时，，一个是切换动画完成时，，当时是考虑到切换动画的时间不同而选择调用两次的。。就等同于 onStart, onComplete,,你可以选择判断状态来完成你的需求。。。动画开始是type='before', 结束时是 type='after',,,感谢你的反馈。。。
