### ISSUE TITLE
BannerAnim onChange 以前是回调两次现在改成一次了么?

### ISSUE THREAD

**Issue by a879475908123** [ant-design/ant-motion#195]
之前是有两个类型..现在只有before了 ..是更新了么作者大大

**Comment by a879475908123** [comment]
@jljsj33

**Comment by jljsj33** [comment]
没有啊。。。我看看。。

**Comment by jljsj33** [comment]
https://codesandbox.io/s/619vx5m7kw，仍然是有两个，你检查一下你的代码吧。。

**Comment by a879475908123** [comment]
好的.谢谢..我看看

**Comment by a879475908123** [comment]
我在onchange里面加了一个回调..回调里面写了2个请求..这样写他就不会调用第二次回调了..只有before,我感觉很奇怪啊.作者大大.你知道怎么回事么

**Comment by a879475908123** [comment]
console.log(direction, index)
        const { callback } = this.props;
        // if (this.state.idx != index) {
        //     this.setState({
        //         idx: index,
        //     })
            // callback && callback(this.state.arr[index])
        // }
        this.setState({
            init: !this.state.init
        })

**Comment by a879475908123** [comment]
我在onchange里面加了一个回调..回调里面写了2个请求..这样写他就不会调用第二次回调了..只有前，我感觉很奇怪啊。作者大大。你知道怎么回事么

**Comment by a879475908123** [comment]
![6egj mxyc63ai rb5y08avf](https://user-images.githubusercontent.com/44834460/48172948-ade7e980-e33c-11e8-9e1c-3598a8b444e0.png)

**Comment by a879475908123** [comment]
![0e1i h1xj7d nr6w 8v 3c5](https://user-images.githubusercontent.com/44834460/48172969-c22be680-e33c-11e8-983e-170c645db576.png)

**Comment by a879475908123** [comment]
已经找到解决办法了..谢谢作者了
