### ISSUE TITLE
ScrollAnim 的 OverPack和Link标签冲突

### ISSUE THREAD

**Issue by 503710847** [ant-design/ant-motion#196]
问题代码
链接部分代码
&lt;div>

&lt;Link to={"content_2_0"} toHash={false}>关于1 </Link>
&lt;OverPack
        replay
        playScale={[0.3, 0.1]}
       {...props}
      >
&lt;Link to={"content_2_0"} toHash={false}>关于2 </Link>
&lt;/OverPack>

&lt;/div>

链接目标代码：

      &lt;Content1 id="content_2_0" key="content_2_0" isMobile={this.state.isMobile}/>,

问题：
点击【关于1】 动效正常，能完整显示 Content1 
点击【关于2】只到了 Content1 的顶部，
去掉 playScale={[0.3, 0.1]} 点击 【关于2】到  Content1  中间

**Comment by jljsj33** [comment]
能提供完整代码吗？这样看不出什么问题的。。。

**Comment by jljsj33** [comment]
是不是这个问题？？？https://github.com/react-component/scroll-anim/issues/38

**Comment by 503710847** [comment]
您好，和您刚才发的网址的不太一样，完整代码我怎么发给您

**Comment by jljsj33** [comment]
直接贴上来啊

**Comment by 503710847** [comment]
请看文件Content0.jsx，关于1是正常的，关于2点击显示不正常，请帮忙指导下，辛苦！




import React, {PropTypes} from 'react';
import {Button, Icon,Modal} from 'antd';
import QueueAnim from 'rc-queue-anim';
import TweenOne from 'rc-tween-one';
// import OverPack from 'rc-scroll-anim/lib/ScrollOverPack';
import logoCenter from '../../assets/img/logo48.png'
import ScrollAnim from 'rc-scroll-anim';

const Link = ScrollAnim.Link;
const OverPack = ScrollAnim.OverPack;

class Content extends React.Component {
/*  state = {visible:false}
  showModal = ()=> {
    this.setSate=({
      visible:true
    })
  }*/
  render() {
    const props = {...this.props};
    delete props.isMobile;
    return (
      <div>
        <div style={{"textAlign":"center","background":"#ffffff"}}>
          <h1>
            <Link
              to={"content_2_0"}
              toHash={false}
            >
              关于1
            </Link>
          </h1>
        </div>

      <OverPack
        replay
        playScale={[0.3, 0.1]}
       {...props}
      >
        <QueueAnim
          type={['bottom', 'top']}
          delay={200}
          className={`${props.className}-wrapper`}
          key="text"
          id={`${props.id}-wrapper`}
        >
          <span
            className="title"
            key="title"
            id={`${props.id}-title`}
          >
            <img width="60%" src={logoCenter}/>
          </span>
          <p
            key="content"
            id={`${props.id}-content`}
          >
            动岚未来，将一切化繁为简，打造智能的健身健身服务系统
          </p>
          <h1>
            <Link style={{"color":"#fff"}}
              to={"content_2_0"}
              toHash={false}
            >
              关于2
            </Link>
          </h1>

          <Button type="ghost" key="button" id={`${props.id}-button`} onClick={()=>{
          // props.webRouter.push("/#content_2_0");
          }}  >
          在线咨询
          </Button>
          {/*<Button type="ghost" key="button" id={`${props.id}-button`} onClick={()=>{*/}
          {/*// props.webRouter.push("/#content_2_0");*/}
          {/*}}  >*/}
          {/*关于我们*/}
          {/*</Button>*/}
        </QueueAnim>

        <TweenOne
          animation={{y: '-=20', yoyo: true, repeat: -1, duration: 1000}}
          className={`${props.className}-icon`}
          key="icon"
        >
          <Icon type="down"/>
        </TweenOne>
      </OverPack>
      </div>
    );
  }
}

Content.propTypes = {
  className: PropTypes.string,
};

Content.defaultProps = {
  className: 'banner0',
};

export default Content;

**Comment by 503710847** [comment]
您好，我已经上传git上
git网址：https://github.com/503710847/ant-motion-dva-cli-example-2.0
位置：https://github.com/503710847/ant-motion-dva-cli-example-2.0/blob/master/src/routes/Home/Content0.jsx

**Comment by jljsj33** [comment]
```jsx
<h1 key="link">
              <Link
                style={{ color: '#fff' }}
                to="content_2_0"
                toHash={false}

              >
                关于2
            </Link>
            </h1>
```

加 key, 可能是 OverPack 里将不带 key 的元素直接移除了，，所以导致动画也被直接移除，，加下 key 会在出场结束后再去移除，出场的动画时间跟滚动的时间相同就没有问题。。。

**Comment by jljsj33** [comment]
还有 Link 是有个 component 的,,可以这么写
```jsx
<Link
  style={{ color: '#fff' }}
  to="content_2_0"
  toHash={false}
  component="h1"
  key="h1"
>
  关于2
</Link> 
```

**Comment by jljsj33** [comment]
模板这块用 [landing](https://landing.ant.design/index-cn) 吧，，那是最新的规范。。。。

**Comment by 503710847** [comment]
嗯呐 感谢
