### ISSUE TITLE
请教下演示的制作方法

### ISSUE THREAD

**Issue by liurq** [ant-design/ant-motion#20]
动画做的很好，很喜欢，想请教一下演示例子的一些技巧
这个页面 http://motion.ant.design/language/transition
我看到你用了个.mp4，来做演示，请教下这个mp4是咋弄的，
我猜想：
 1 里面的内容效果是先写个网站【感觉这样太费时间了】，然后用视频录制？  
 2 是不是有咋工具可以方便操作这样的演示的？

方便指导一下吗？

**Comment by jljsj33** [comment]
演示是 AE 做的。。。

**Comment by jljsj33** [comment]
最好找个设计师来做这玩意，

**Comment by liurq** [comment]
明白了，谢谢你，我还以为有咋界面编辑工具，程序员也可以弄呢
