### ISSUE TITLE
换肤遇到的问题

### ISSUE THREAD

**Issue by v5zz** [ant-design/ant-motion#201]
版本：
antd:'^3.7.0',
"webpack": "^3.12.0",
配置如下：
1.generateColorLess.js
 `const path = require('path');
const {generateTheme, getLessVars} = require('antd-theme-generator');

const options = {
  stylesDir: path.join(__dirname, 'src/styles'),
  antDir: path.join(__dirname, 'node_modules/antd'),
  varFile: path.join(__dirname, 'src/styles/vars.less'),
  mainLessFile: path.join(__dirname, 'src/styles/main.less'),
  themeVariables: [
    '@primary-color',
  ],
  indexFileName: 'index.html',
  outputFilePath: path.join(__dirname, 'theme/color.less'),
}

generateTheme(options)
`
2.styles/vars.less
`//vars.less
@import "~antd/lib/style/themes/default.less";
@import "../assets/less/_variables";

@primary-color: #1c8acd;
:root {
  --themeColor: @primary-color; 
}`

3.index.html

`<!DOCTYPE html>
<html lang="en">
<head>
  <title>换肤</title>
  <meta charset="utf-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"/>
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-touch-fullscreen" content="yes"/>

</head>
<body>

<div id="root">loading...</div>
<link rel="stylesheet/less" type="text/css" href="theme/color.less"/>
<script>
  window.less = {
    async: true,
    env: 'production'
  };
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
</body>
</html>
`

按照这个配置页面
![image](https://user-images.githubusercontent.com/47095302/51900372-1ac8c800-23f0-11e9-9781-81f9a7390780.png)

**Comment by jljsj33** [comment]
我觉得你这问题应该提到 ant-design 里去。。。或者仔细阅读下  [ant-design 的定制主题](https://ant.design/docs/react/customize-theme-cn)
