### ISSUE TITLE
banner 鼠标拖动切换失败

### ISSUE THREAD

**Issue by Y-qwq** [ant-design/ant-motion#214]
当鼠标按下向某一方向拖动，再拖回原处松开鼠标（即拖动了一段距离但没达到切换要求的距离时），复位后就会卡死了，无法再切换了，直接官方例子就有这样的问题了。
[官方例子](http://react-component.github.io/banner-anim/examples/bgParallax.html)

**Comment by Y-qwq** [comment]
还有，为什么按住向右滑动，轮播的图组不应该是向左切换的吗= =，类似[swiper](https://www.swiper.com.cn/demo/index.html)这种才比较符合常理吧。或者提供一个api选项设置？

**Comment by jljsj33** [comment]
v2.2.7, 滑动方向也改了，是反了。。。
