### ISSUE TITLE
Banner动画组件报错

### ISSUE THREAD

**Issue by MyPacker** [ant-design/ant-motion#216]
index.js:1 Warning: Prop `style` did not match. Server: "display:block;position:absolute;width:100%;null:" Client: "display:block;position:absolute;width:100%;transform:"

**Comment by jljsj33** [comment]
请提供下重现，，谢谢。。。https://codesandbox.io/s/619vx5m7kw

**Comment by MyPacker** [comment]
jsx如下：
`<BannerAnim
                prefixCls={styles['teacher-info']}
                type="across"
                duration={1000}
                arrow={false}
                thumb={false}
                ease="easeInOutExpo"
                ref={c => {
                  this.bannerText = c;
                }}
                onChange={this.onChange}
                dragPlay={false}
                autoPlaySpeed={1000}
              >
                {textChildren}
              </BannerAnim>`
textChildren节点：
`const textChildren = teacherList.map((item, i) => (
      <Element
        key={i}
        followParallax={{
          delay: 1000,
          data: [{ id: 'teacher', value: 50, type: 'x' }, { id: 'content', value: -30, type: 'x' }],
        }}
      >
        <QueueAnim type="bottom" duration={1000} delay={[!i ? this.state.delay + 500 : 800, 0]}>
          <div className={styles.title} key="teacher">
            {item.name}
            <div className={styles.desc}>{item.company}</div>
          </div>
          <div className={styles.content} key="content">
            {item.description}
          </div>
        </QueueAnim>
      </Element>
    ));`

报错信息：
`Warning: Prop style did not match. Server: "display:block;position:absolute;width:100%;null:" Client: "display:block;position:absolute;width:100%;transform:"`
报错位置渲染之后的源码（项目是基于next.js的SSR多页）
`<div class="banner-anim _33ZDJvVyenyi9R5dtimz7B">
          <div style="display:block;position:absolute;width:100%;null:" class="banner-anim-elem">
           <div></div>
          </div>
          <div style="display:none;position:absolute;width:100%;null:" class="banner-anim-elem"></div>
          <div style="display:none;position:absolute;width:100%;null:" class="banner-anim-elem"></div>
          <div style="display:none;position:absolute;width:100%;null:" class="banner-anim-elem"></div>
          <div style="display:none;position:absolute;width:100%;null:" class="banner-anim-elem"></div>
          <div style="display:none;position:absolute;width:100%;null:" class="banner-anim-elem"></div>
         </div>`

**Comment by jljsj33** [comment]
服务端渲染的这种警告没卵关系的，前端能跑就行了，，这种应该警告不会在线上出现的。。。

**Comment by wvit** [comment]
可以通过 suppressHydrationWarning 属性来抑制不可避免的水合不匹配错误
