### ISSUE TITLE
Link is broken on official antMotion site for ListSort demo

### ISSUE THREAD

**Issue by mxye** [ant-design/ant-motion#217]
See this demo page: https://motion.ant.design/exhibition/demo/list-sort

When I click on "Component URL", which points to 
https://github.com/ant-design/ant-motion/blob/master/src/edit/template/components/ListSort.jsx

I get a "404 not found". So where can one actually import the Component like in the code snippet:
`import ListSort from '../../site/theme/template/other/ListSort'`?

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-motion/commit/5086d80633dd87c013ab010c6283e58a6a1ea060
