### ISSUE TITLE
怎么实现tab切换的动画？

### ISSUE THREAD

**Issue by chenbosns** [ant-design/ant-motion#218]
出现的问题是，上一个tab还未消失，下一个tab已经出现，导致下一个tab从下方出现，而且撑高容器

**Comment by jljsj33** [comment]
http://motion.ant.design/exhibition/demo/table-enter-leave-cn

**Comment by jljsj33** [comment]
样式看仔细，，必须破坏 tab 特性，不想破坏就没办法。。
