### ISSUE TITLE
SSR下轮播图样式异常

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-motion#222]
https://www.lsz8617.com/
![image](https://user-images.githubusercontent.com/35049517/61674527-cb23e300-ad26-11e9-908f-843b4bb477e7.png)
生产模式会这样，开发模式没问题

**Comment by Fled8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/61917006-978ec600-af7d-11e9-937f-224d63ca4524.png)
![image](https://user-images.githubusercontent.com/35049517/61917022-b55c2b00-af7d-11e9-888d-eff5d4f89635.png)
   @jljsj33 感谢帮忙修复，但是刚才试了一下还有两个问题，在这两种动画下会出现高度问题

**Comment by jljsj33** [comment]
开发模式没问题，线上有问题。。。有点难搞，没法在开发模式下重现。。。暂时把这两种轮播去掉吧。。。type={['across', 'vertical', 'acrossOverlay', 'verticalOverlay']}

**Comment by Fled8617** [comment]
好的，暂时也是这么处理的，代码就是demo中随鼠标移动那段代码原封不动拿过来的，感觉跟生产环境的chunkcss有点关系，纯属个人猜测 @jljsj33

**Comment by jljsj33** [comment]
你的样式是怎么加载的，，我本地 build 的也没问题啊。。。

**Comment by jljsj33** [comment]
你在本地 build 完后，start 后有没问题???

**Comment by jljsj33** [comment]
![image](https://user-images.githubusercontent.com/6802825/61925698-0a109d80-afa0-11e9-8737-c9eac9d6573b.png)

![image](https://user-images.githubusercontent.com/6802825/61925702-109f1500-afa0-11e9-838c-30c7a20e1133.png)

本地用 build 的，console.log 的高还是 220 啊。。

**Comment by jljsj33** [comment]
在 node_modules 里的 rc-banner-anim 里的 es 包里的打个 logo 再 build 看看。。。

![image](https://user-images.githubusercontent.com/6802825/61925795-6a9fda80-afa0-11e9-95f3-129a074fd37a.png)

**Comment by Fled8617** [comment]
同一段代码，打包出来不断刷新打印的数值有时候不一样
![image](https://user-images.githubusercontent.com/35049517/61926386-ef8bf380-afa2-11e9-895c-e9ddbe3fadaf.png)
![image](https://user-images.githubusercontent.com/35049517/61926407-00d50000-afa3-11e9-8be6-1392797cf2fa.png)
样式自己写的部分用的globaljsx
![image](https://user-images.githubusercontent.com/35049517/61926433-2235ec00-afa3-11e9-8b8b-1774b3d771fc.png)
其他部分按照官方的demo引入的
![image](https://user-images.githubusercontent.com/35049517/61926459-35e15280-afa3-11e9-9d5d-7b31f3323c8a.png)

**Comment by Fled8617** [comment]
@jljsj33

**Comment by jljsj33** [comment]
你把你这项目放 git 上，给我看看，，，我这输出就是 220

**Comment by Fled8617** [comment]
https://github.com/Fled8617/next-ant-motion.git
准备了一个repo,我发现了一个问题，最终打包出只有一个style.chunk是没问题的，如果打包出两个就会是不是复现这个问题，貌似是antd样式的问题，这个repo应该装完可以直接启动，我把断点代码已经build好了一份
 @jljsj33 ![image](https://user-images.githubusercontent.com/35049517/61936485-6fc05200-afbf-11e9-939c-23240b560a36.png)

**Comment by jljsj33** [comment]
用 2.3.0

**Comment by Fled8617** [comment]
ok,目前没有发现其他问题，非常感谢
