### ISSUE TITLE
scrollScreen: 启动整屏滚动无效

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-motion#236]
`
 useEffect(() => {
    // 实现整屏滚动
    const docHeight = dom.current.getBoundingClientRect().height;
    console.log('docHeight', docHeight);
    scrollScreen.init({ docHeight });
    // 适配手机屏幕;
    enquireScreen(b => {
      setMobile(!!b);
    });
  }, []);
`

![image](https://user-images.githubusercontent.com/12181423/63244461-07981f80-c290-11e9-9dee-09830c8b9c59.png)

没有quan ping全屏滚动
![image](https://user-images.githubusercontent.com/12181423/63244479-1b438600-c290-11e9-80fe-6f64fadd9f56.png)

**Comment by jljsj33** [comment]
只支持 web 端的，，无线端的暂不支持，，如果你有兴趣可以给我们来个 pr 加下，，只需把事件加上即可。。。
