### ISSUE TITLE
很好奇的说

### ISSUE THREAD

**Issue by hanxu317317** [ant-design/ant-motion#24]
在git上查看react 动画解决方案的时候.无意中看到你们的rc-tween-one库.你们是自己写着玩的?还是公司的项目??

**Comment by jljsj33** [comment]
怎么了？写的不好吗？

**Comment by jljsj33** [comment]
公司的项目。如果动画的底层写的不好。。。可以指点指点。。

**Comment by hanxu317317** [comment]
写的挺不错的.最近公司要求用动画,想着是自己写.还是引包~~就看到你们的包了.还在研究中.以后还得请教你们.

**Comment by hanxu317317** [comment]
现在阿里的人这么难混么...'设计师写码，我容易嘛我。。。'设计师都要写代码还是用比较新的技术react~

**Comment by hi-caicai** [comment]
@hanxu317317 哈哈，因为设计师有更好的动画感觉。所以自己来写呗。哈哈
