### ISSUE TITLE
TS引用报错

### ISSUE THREAD

**Issue by wzh19940000** [ant-design/ant-motion#243]
![image](https://user-images.githubusercontent.com/20918643/64148738-9d1ddc80-ce56-11e9-842b-bc64bb482fc9.png)
使用ts报错没有d.ts文件，希望完善

**Comment by jljsj33** [comment]
这种在 package.json 里加个 typings 或在 tslint 过滤掉就行了，，没必要加这个，，如果你需要，，可以 pr 来加下
