### ISSUE TITLE
一点小疑问

### ISSUE THREAD

**Issue by monkingxue** [ant-design/ant-motion#25]
Tween的单元素动画是不是不能对组件施加？我对Tween的子组件加了旋转的效果，结果不是绕着自身中心而是屏幕中心旋转

**Comment by jljsj33** [comment]
请提供代码。。。。

**Comment by monkingxue** [comment]
`<TweenOne animation={{top: top, duration: time, delay: delay, type: 'to'}}
                  paused={paused} reverse={reverse}
                  style={{position: 'relative', top: offset}}>
          <div className="align-center flex-col">
            <FloatingActionButton mini={true} onMouseEnter={this.handleCoverIn}
                                  onMouseLeave={this.handleCoverOut} children={this.props.children}>
            </FloatingActionButton>
          </div>
        </TweenOne>`
这个代码工作正常了，不过当Tween内包着material-UI 的Icon时，icon如果不设置颜色那么颜色会被改变

**Comment by jljsj33** [comment]
不懂你的意思。。。。TweenOne 只对当前的标签进行 style 操作。。。children 是不受影响的。。你仔细检查下你的样式
