### ISSUE TITLE
关于nav自动折叠显示问题

### ISSUE THREAD

**Issue by demon-zhonglin** [ant-design/ant-motion#257]
你好。
能否讲解一下是如何自动折叠吗？看生成的 Nav.jsx 代码中似乎并没有相关的。还有生成的 html 内容有一处不太理解（在Nav.jsx中没有找到相关生成的代码）如下图: 
![image](https://user-images.githubusercontent.com/25782728/67735259-8d79d900-fa3e-11e9-8b0f-a43a62f191ce.png)
十分感谢.

**Comment by jljsj33** [comment]
这个你去了解下 ant-design 的 menu 吧。。。https://ant.design/components/menu-cn/

**Comment by jljsj33** [comment]
menu 里的每个 item 都会有个占位符，，三个点的那个
