### ISSUE TITLE
scrollscreen向上滚多屏

### ISSUE THREAD

**Issue by mantutu** [ant-design/ant-motion#259]
scrollscreen向下滚是正常的，向上翻页时会滚动两屏

**Comment by jljsj33** [comment]
麻烦提重下重现步骤。。。

**Comment by jljsj33** [comment]
v3.7.1 已修复，，，chrome 对 Wheel/Mousewheel 的 preventDefault 的处理也搞成 {passive: true } 了，所以拦不掉了。。。https://www.chromestatus.com/feature/6662647093133312
