### ISSUE TITLE
在next本地使用可以,部署报错window is not defined

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-motion#260]
{ ReferenceError: window is not defined
20:19:36     at getPassive (/home/jkuser/workspace/dev-node-website/node_modules/rc-scroll-anim/lib/util.js:126:3)
20:19:36     at Object.<anonymous> (/home/jkuser/workspace/dev-node-website/node_modules/rc-scroll-anim/lib/ScrollScreen.js:39:36)
20:19:36     at Module._compile (internal/modules/cjs/loader.js:689:30)
20:19:36     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
20:19:36     at Module.load (internal/modules/cjs/loader.js:599:32)
20:19:36     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
20:19:36     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
20:19:36     at Module.require (internal/modules/cjs/loader.js:637:17)
20:19:36     at require (internal/modules/cjs/helpers.js:22:18)
20:19:36     at Object.<anonymous> (/home/jkuser/workspace/dev-node-website/node_modules/rc-scroll-anim/lib/index.js:30:21) type: 'ReferenceError' }

**Comment by jljsj33** [comment]
感放反馈

**Comment by XinYueXiao** [comment]
是要下载这个依赖吗

**Comment by jljsj33** [comment]
依赖删了重装就可以了，，线上重新布署
