### ISSUE TITLE
动画效果在ie浏览器使用报错

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-motion#261]
![image](https://user-images.githubusercontent.com/31272499/69019865-7a2ead80-09ed-11ea-8504-0bb1753266f2.png)

解决方案添加了polyfill
<script src="https://polyfill.io/v3/polyfill.js?features=es5,es6,es7&flags=gated" />

是否能统一处理下类似问题

**Comment by jljsj33** [comment]
这个兼容不需要统一处理，，一般现在写 es6 的兼容 ie 都会带上 polyfill.js
