### ISSUE TITLE
import { Link } from 'rc-scroll-anim' 在移动端使用定位不准

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-motion#262]
不会定位到指定位置,
第一次点击会定位到目标上方
第二次定位到目标

**Comment by XinYueXiao** [comment]
为啥hash 设置的是10 自己变成12 了

**Comment by XinYueXiao** [comment]
只点到10 在点12才能是12

**Comment by XinYueXiao** [comment]
在PC的宽度变小的时候也会这样

**Comment by jljsj33** [comment]
区块高度在滚动的时间发生变化了，可以给区块设定个 height 或 min-hieght，，

**Comment by XinYueXiao** [comment]
我设置了height,定位依旧不准,我输出了hash
content_12在上
content_10在下
我点击content_10显示了一下content_10,刹那自己变成了content_12
这是效果图
http://chuantu.xyz/t6/703/1574062101x3703728804.gif

**Comment by jljsj33** [comment]
content_10 是最后一屏？？？且高度不够 50% 吗？？

**Comment by XinYueXiao** [comment]
不是,中间部分也这样
在手机上调试本地,会显示一下下面的然后滚上去

**Comment by XinYueXiao** [comment]
按照页面加载顺序一个一个点才能定位成功,如果在第一个位置点第四个,就会在第四个那闪一下,跑到第三个

**Comment by jljsj33** [comment]
能提供下重现 demo 吗，，，我这边重现不了 https://stackblitz.com/edit/react-bzkoaj

**Comment by XinYueXiao** [comment]
http://www.weiboyi.com/activity

**Comment by jljsj33** [comment]
就是滚动时高度变化的问题，，最简单的解决办法就是给每个区块设置个 min-hieght ...

**Comment by XinYueXiao** [comment]
加了
别的好使,最后一个不好使
在小的窗口下那个也不好使
row col 4->8啥的

**Comment by XinYueXiao** [comment]
尤其是iphone7

**Comment by jljsj33** [comment]
行数也能算出来的吧。。

**Comment by jljsj33** [comment]
xs md 是你控制的。。

**Comment by jljsj33** [comment]
2.7.4 用动画时获取高度了，，可以解决这问题，

**Comment by jljsj33** [comment]
还有你那个地图上点的阴影错位了

**Comment by XinYueXiao** [comment]
感谢大佬，👍👍👍👍👍
