### ISSUE TITLE
样式文字错乱了

### ISSUE THREAD

**Issue by lijiuhui** [ant-design/ant-motion#263]
原本样式是这样：
![image](https://user-images.githubusercontent.com/20593385/69123458-64e47c80-0adc-11ea-8074-5726fcd2fb8a.png)

点击编辑文本后变成了：
![image](https://user-images.githubusercontent.com/20593385/69123476-70d03e80-0adc-11ea-84d3-e4c0b464e0fc.png)

求助，谢谢。

**Comment by jljsj33** [comment]
额，，等两分种，，

**Comment by lijiuhui** [comment]
> 额，，等两分种，，

非常感谢，已经可以了。
