### ISSUE TITLE
TweenOne PathPlugin 报错

### ISSUE THREAD

**Issue by HeatonZ** [ant-design/ant-motion#264]
用的是例子：https://motion.ant.design/api/tween-one-cn

Cannot set property 'transform' of undefined

https://stackblitz.com/edit/react-2cs4we

**Comment by jljsj33** [comment]
对不起，api 里写错了，，哈哈，，谢谢哦，，一般都是拷 demo 里的代码的。。

**Comment by HeatonZ** [comment]
@jljsj33 svg去掉之后，component="path" 也应该去掉吧

里面的元素上下移动时如何保持不旋转，仅上下移动时会旋转90°
`this.data.rotate = Math.atan2(p1.y - p0.y, p1.x - p0.x) * 180 / Math.PI;`

https://stackblitz.com/edit/react-pd2uon?file=index.js

**Comment by jljsj33** [comment]
没看懂，，啥上下移动时不旋转，又公款上下移动时会旋转

**Comment by HeatonZ** [comment]
path = "M30,100 v-100"

`
<TweenOne animation={{ path, repeat: -1, yoyo: true }}>123</TweenOne>
`
// 这段代码123会旋转90°



   ```
 <TweenOne
      animation={{ path: { x: path, y: path }, repeat: -1, yoyo: true }}
    >
      321
    </TweenOne>
```
// 这段代码321不会旋转

**Comment by jljsj33** [comment]
没错啊，，第二段里面没有给 rotate，当然不旋转啊。

**Comment by jljsj33** [comment]
path 为 string 时，，将会触发三个参数，，x, y, rotate,
