### ISSUE TITLE
组件包裹的dom在网页中显示不出来

### ISSUE THREAD

**Issue by littleEmi** [ant-design/ant-motion#266]

**Comment by vickychu** [comment]
升级了react版本之后 我碰到了同样的问题

**Comment by littleEmi** [comment]
> 升级了react版本之后 我碰到了同样的问题
你找到解决方法了吗?

**Comment by vickychu** [comment]
> > 升级了react版本之后 我碰到了同样的问题
> > 你找到解决方法了吗?

并没有 今天刚升级发现的 之前是好的

**Comment by jljsj33** [comment]
fix  https://github.com/react-component/tween-one/commit/ad98a3b5e7066d3c892d01a7a490c6b99ea52d75

**Comment by Athrun-Judah** [comment]
我用firefox正常显示，用chrome却显示不出来，请问你解决了吗？
