### ISSUE TITLE
如何在动画标签中通过子组件的ref调用ref 的方法？

### ISSUE THREAD

**Issue by bmmanmyt** [ant-design/ant-motion#267]
![image](https://user-images.githubusercontent.com/46342554/70692270-edc69080-1cf5-11ea-8659-b0b21f41ba7b.png)
提示是这样的，问题很幼稚，还望解答。
代码如下
![image](https://user-images.githubusercontent.com/46342554/70692332-151d5d80-1cf6-11ea-9c4c-ce4dc71056b8.png)

**Comment by bmmanmyt** [comment]
看不到图片，报错信息：
index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `TweenOne`.

代码：如下结构
     <QueueAnim >
          <Edit ref="edit"/>
     <QueueAnim >

**Comment by bmmanmyt** [comment]
<QueueAnim >
         <Edit  ref="edit" />
     </QueueAnim >

**Comment by bmmanmyt** [comment]
已经解决了，感谢。

**Comment by jljsj33** [comment]
有个 childRefs， 
<QueueAnim ref={c => this.c = c } onEnd={() => { console.log( this.c.childRefs);  }/>

**Comment by Yixeu** [comment]
我在fc组件下使用 QueueAnim 标签也遇到了这个问题。 QueueAnim 底层代码为什么会获取一次ref，我本身子组件并没有使用ref，因为fc组件不支持
