### ISSUE TITLE
English version of docs

### ISSUE THREAD

**Issue by andreystarkov** [ant-design/ant-motion#27]
Can i look for it somewhere? If it doesnt exists please create it. Your solution is awesome. World waits ;)

**Comment by hi-caicai** [comment]
@andreystarkov I'm sorry,  we have no time to write English documents. It will be provided later。

**Comment by sundaypig** [comment]
请问单元素动画是否可以组合呢，例如进行曲线动画同时也进行缩放？

**Comment by jljsj33** [comment]
@sundaypig 你能新起个 issues 再提问吗，，，不要在别人的 issues 上问不同的问题。。。

贝赛尔不行，，path 曲线是可以的

**Comment by jljsj33** [comment]
https://github.com/react-component/tween-one/commit/715b18e2fe8973b227158de0d43e8da6b1edf256#diff-bbfb3b66f91e10b82d04087f40353e99L518 这里改掉了，，所以不能共同用了。。。下个版本将去掉贝赛尔曲线，，建议用 path 曲线。。
