### ISSUE TITLE
响应式布局，请教如何把 ant-design 的栅格系统集成到 ant-motion 的 template 里？

### ISSUE THREAD

**Issue by librae8226** [ant-design/ant-motion#28]
先赞一下 ant-motion 的模版，十分好用，目前希望支持响应式布局。

按照 ant-design 栅格的使用方式，可以用下面的方式来做响应式适配：
```
import { Row, Col } from 'antd';

ReactDOM.render(
  <Row>
    <Col xs={2} sm={4} md={6} lg={8}>Col</Col>
    <Col xs={20} sm={16} md={12} lg={8}>Col</Col>
    <Col xs={2} sm={4} md={6} lg={8}>Col</Col>
  </Row>
, mountNode);
```

而比如在模版的 **Content2** 和 **Content5** 中，不太清楚应该如何来做？

Content2: 多个文字段落
Content5: 多个文字段落+图片

是否可以给个简单的参考样例？

**Comment by jljsj33** [comment]
谢谢你的建议，，由于目前模板这块暂时还是处于测试阶段，所以没有考虑到响应式布局，我们后期会考虑响应式布局和无线端的呈现。。

**Comment by librae8226** [comment]
@jljsj33 了解了，谢谢

**Comment by jljsj33** [comment]
目前如果要应映式，可以直接套用 row  的样式。。。 ant-row,,,ant-col-xxx
