### ISSUE TITLE
ant motion 自由模板搭配改版

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-motion#29]
- [x] 编辑区块的一个调整，目前直接在页面里调整模块与编辑。
<img src="https://zos.alipayobjects.com/rmsportal/hGLELiHAIdefWMItogNXamLUkrmkgtje.png" />

**Comment by oqq5518** [comment]
我使用了模板生成的代码，然后把Home文件夹导入到官方提供的文件夹。
现在报错，找不到less模块。
![image](https://cloud.githubusercontent.com/assets/4516065/20654551/7550dc42-b555-11e6-8939-b8490587b083.png)

**Comment by jljsj33** [comment]
额。。是叫你把 less 内容全放在:global{}里面.

https://github.com/css-modules/css-modules#usage-with-preprocessors

**Comment by jljsj33** [comment]
第一句改成： @import '../custom.less'

**Comment by oqq5518** [comment]
![image](https://cloud.githubusercontent.com/assets/4516065/20655973/a1c2a91a-b562-11e6-9078-fc07d308b9b9.png)
是这样弄吗？

**Comment by oqq5518** [comment]
![image](https://cloud.githubusercontent.com/assets/4516065/20656246/92579c3a-b565-11e6-967b-0d334ebd9865.png)

**Comment by jljsj33** [comment]
额。。这错误看不懂吗？？？？你去把 Point.jsx 和 Content4.jsx里的less路径改下。。。

怎么会没有替换，，更新后可能出错了。。。

还有，，以后有问题可以新起个 issues...

**Comment by jljsj33** [comment]
照你这路径应该是 './less/point.less'

**Comment by jljsj33** [comment]
`@inport './custom.less'` 不要放到 :global 里
