### ISSUE TITLE
rc-banner-anim 不兼容antd4  

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-motion#290]
"rc-banner-anim": "^2.4.2", 轮播图不显示 访问成功后等一会页面会崩溃

What is expected?
解决bug

What is actually happening?
页面 样式混乱， 轮播图不显示 页面会崩溃

Environment	Info
antd	4.0.0
React	16.8.6
System	centos
Browser	chrome 80.0.3987.122（正式版本） （64 位）
@kzabc
 
Author
kzabc commented on 3 Mar
image
image

**Comment by jljsj33** [comment]
banner-anim 并没有依赖 antd，不兼容个鬼？？？
