### ISSUE TITLE
Cannot find module "react/lib/CSSProperty";use react@15.4.0

### ISSUE THREAD

**Issue by havefive** [ant-design/ant-motion#32]
Try fix it or update package.json: "react": "15.3.x"

**Comment by jljsj33** [comment]
fixing，thx

**Comment by afc163** [comment]
没修复不要关闭。

**Comment by jljsj33** [comment]
修了啊

**Comment by jljsj33** [comment]
[7e8ebde40277654282e6deb6469afc043daf3e56](https://github.com/jljsj/style-utils/commit/7e8ebde40277654282e6deb6469afc043daf3e56)

**Comment by afc163** [comment]
提交的时候要关联 issue。

**Comment by afc163** [comment]
另外，`fixing` 是什么意思。

**Comment by jljsj33** [comment]
fixed
