### ISSUE TITLE
umi项目使用QueueAnim可以用来做路由跳转的过渡动画么

### ISSUE THREAD

**Issue by wansuiasdn** [ant-design/ant-motion#323]
有没有大佬指点一下，页面跳转后，会出现两个相同页面

**Comment by jljsj33** [comment]
在 layout 组件（layouts/index.js 或者 pages 子目录下的 _layout.js）里在渲染子组件时用 TweenOneGroup 或 QueueAnim 包裹一层，并以 location.pathname 为 key;

给个 TweenOneGroup 的例子吧。。

```jsx
import withRouter from 'umi/withRouter';
import { TweenOneGroup } from 'rc-tween-one';
import styles from './index.less';


const animate = {
  enter: { x: '100vw', ease: 'easeInOutCubic' },
  leave: { x: '-30vw', ease: 'easeInOutCubic' }
};

const Layouts = ({ children, location }) => {
  const { pathname } = location;
  const pathArray = pathname.split('.')[0].split('/');
  const path = pathArray[pathArray.length - 1];
  const key = path || 'index';
  const enter = key === 'index' ? animate.leave : animate.enter;
  const leave = key === 'index' ? animate.enter : animate.leave;

  return (
    <TweenOneGroup
      enter={[
        { type: 'set', zIndex: key === 'index' ? 0 : 1 },
        { ...enter, type: 'from' }
      ]}
      leave={[{ type: 'set', zIndex: key === 'index' ? 1 : 0 }, leave]}
      appear={false}
      className="app-layout"
    >
      {/* React.cloneElement(children, { key }) */}
      <div key={key} className={styles.layoutAnimChild}>{children}</div>
    </TweenOneGroup>
  );
};

export default withRouter(Layouts);

```

**Comment by wansuiasdn** [comment]
@jljsj33  谢谢大大，学习了，感谢！
![biu](https://user-images.githubusercontent.com/47979542/83230537-7bbb0880-a1bc-11ea-936c-9047c43b69d2.jpg)

**Comment by wansuiasdn** [comment]
@jljsj33 emmmm给的demo也存在这个bug，即页面跳转后，结束动画的组件与开始动画的组件都会被更新为最新的组件，比方说a页面->b页面  那么结束动画应该是a ，开始动画是b ，但播放结果是 b->b

**Comment by jljsj33** [comment]
```css
.tween-one-leaving {
  position: absolute;
  width: 100%;
}
```
加上这个

**Comment by wansuiasdn** [comment]
@jljsj33 这个加过了，加这个是为了避免刷出两个组件出现错位的情况，= = 现在的问题是，被替代的页面与要加载的页面都被更新成了最新的页面，就是说a页面要播放被替换动画，b页面要播放加载动画，但当路由跳转之后，a页面被更新成了b页面播放被替换动画，b页面播放加载动画

**Comment by jljsj33** [comment]
加了 Strict Mode 吗？

**Comment by jljsj33** [comment]
换成 QueueAnim 看看。。http://react-component.github.io/queue-anim/examples/router.html#/page1

**Comment by jljsj33** [comment]
v2.7.0

**Comment by zs810379677** [comment]
#

**Comment by liangxiao-zs** [comment]
> @jljsj33 emmmm给的demo也存在这个bug，即页面跳转后，结束动画的组件与开始动画的组件都会被更新为最新的组件，比方说a页面->b页面 那么结束动画应该是a ，开始动画是b ，但播放结果是 b->b

这个问题解决了吗。我用最新的v2.7.3遇到的也是这样的问题，换成queueAnim也是一样的

**Comment by wansuiasdn** [comment]
@liangxiao-zs  大佬这个问题解决了么

**Comment by wansuiasdn** [comment]
@jljsj33 动画交替的两个页面都被更新成最新的页面了。

**Comment by wansuiasdn** [comment]
> 换成 QueueAnim 看看。。http://react-component.github.io/queue-anim/examples/router.html#/page1

大佬这个demo里需要重新编写route配置文件，并且引入所有页面，我在umi都写在umirc下面了，有木有什么办法可以解决的

**Comment by jljsj33** [comment]
上面写的 TweenOneGroup 的就是 umi 里用的啊，，layout 上加啊

**Comment by jljsj33** [comment]
https://github.com/ant-motion/landing-umi-example/blob/router/src/layouts/index.js#L35, 在这里套以上代码就可以了啊。。。

**Comment by wansuiasdn** [comment]
> https://github.com/ant-motion/landing-umi-example/blob/router/src/layouts/index.js#L35, 在这里套以上代码就可以了啊。。。

我现在就是最外层一个layout专门放这个动画，内层有个layout写页面公共的布局，现在是切换页面之后，新旧页面都会先被更新成最新的页面，然后再转场动画，就是A->B 会变成 B->B      QAQ

**Comment by jljsj33** [comment]
额，，发现了，，感觉是 hook 跳过了 props 的刷新，，直接改内容了。。

**Comment by jljsj33** [comment]
https://github.com/umijs/umi/blob/master/packages/renderer-react/src/renderRoutes/renderRoutes.tsx#L162
umi 的问题，，，没带 location

**Comment by jljsj33** [comment]
你不急的话可以等 umi 发版，急的话可以改下 Switch,,, demo 你看这个 https://github.com/ant-motion/landing-umi-example/blob/router/src/layouts/index.js#L46

**Comment by wansuiasdn** [comment]
谢谢大佬，不急等更

**Comment by wansuiasdn** [comment]
@jljsj33 哈哈，也不行，页面也会被更新掉，

**Comment by wansuiasdn** [comment]
@jljsj33 import { withRouter, Switch } from 'umi'
import { TweenOneGroup } from 'rc-tween-one';

**Comment by wansuiasdn** [comment]
@jljsj33 import { withRouter, Switch } from 'umi'
import { TweenOneGroup } from 'rc-tween-one';
export default withRouter(({ children, location }) => {
    const animate = {
        enter: { x: '100vw', ease: 'easeInOutCubic' },
        leave: { x: '-30vw', ease: 'easeInOutCubic' }
    };
    console.log(children, location)
    const { pathname } = location;
    const pathArray = pathname.split('.')[0].split('/');
    const path = pathArray[pathArray.length - 1];
    const key = path || 'index';
    const enter = key === 'index' ? animate.leave : animate.enter;
    const leave = key === 'index' ? animate.enter : animate.leave;
    return (
        <TweenOneGroup
            enter={[
                { type: 'set', zIndex: key === 'index' ? 0 : 1 },
                { ...enter, type: 'from' }
            ]}
            leave={[{ type: 'set', zIndex: key === 'index' ? 1 : 0 }, leave]}
            appear={false}
            className="app-layout"
        >
            <div key={key} className="layout-anim-child">
                <Switch location={location}>{children}</Switch>
            </div>
        </TweenOneGroup>

    )
})
我躺好等更新啦

**Comment by wansuiasdn** [comment]
`@jljsj33 import { withRouter, Switch } from 'umi'
import { TweenOneGroup } from 'rc-tween-one';
export default withRouter(({ children, location }) => {
const animate = {
enter: { x: '100vw', ease: 'easeInOutCubic' },
leave: { x: '-30vw', ease: 'easeInOutCubic' }
};
console.log(children, location)
const { pathname } = location;
const pathArray = pathname.split('.')[0].split('/');
const path = pathArray[pathArray.length - 1];
const key = path || 'index';
const enter = key === 'index' ? animate.leave : animate.enter;
const leave = key === 'index' ? animate.enter : animate.leave;
return (
<TweenOneGroup
enter={[
{ type: 'set', zIndex: key === 'index' ? 0 : 1 },
{ ...enter, type: 'from' }
]}
leave={[{ type: 'set', zIndex: key === 'index' ? 1 : 0 }, leave]}
appear={false}
className="app-layout"
>

{children}

)
})
`
我躺好等更新了

**Comment by jljsj33** [comment]
我试了可以才放出来的啊。。你检查下吧，，，照我 demo 的代码，，把 leaving 的  position 设为 absolute;
```css
.app-layout {
  position: relative;
  
}
.layout-anim-child {
  background-color: #fff;
  position: relative;
  min-height: 100vh;
  &.tween-one-leaving {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
  }
}
```

**Comment by wansuiasdn** [comment]
@jljsj33 嘿嘿，我直接拉的大佬的demo整合进去了
![image](https://user-images.githubusercontent.com/47979542/106569374-65492600-656f-11eb-9f4c-c57bc024d84e.png)
![image](https://user-images.githubusercontent.com/47979542/106569481-89a50280-656f-11eb-8c64-add7cf8eefa4.png)
![image](https://user-images.githubusercontent.com/47979542/106569575-ae00df00-656f-11eb-9e5d-234cc80d4d06.png)

**Comment by wansuiasdn** [comment]
代码我就贴在wrappers对应的组件里面了

**Comment by wansuiasdn** [comment]
但是所有页面又都共用了一个layout，不知道是不是这个的原因

**Comment by jljsj33** [comment]
这个我就帮不了你了，，你自个排查吧。。

**Comment by wansuiasdn** [comment]
@jljsj33 哈哈，好的，谢谢大佬

**Comment by wansuiasdn** [comment]
@jljsj33  大佬我写了个会出现问题的简易demo   您有时间可以看一下    
https://dev.cdn.sbnh.cn/test_animate.zip

**Comment by jljsj33** [comment]
这没办法，，Switch 上的加 location 就是为了保存住上个 location，，，你在底下再加个 Switch，所以没有保存住，，location 会在 Switch 里 useLocation 自已获取，，不做保存所有子级都会发生改变。。。

**Comment by jljsj33** [comment]
如果react-router 是可以解的。。。只要在动画组件里的 Switch 都加上 location 就可以了。。

**Comment by jljsj33** [comment]
你可以去 umi 那提，，这不是动画组件的问题，，是脚手架的问题。。

**Comment by wansuiasdn** [comment]
好的，谢谢您，我去那边提个issue

**Comment by jljsj33** [comment]
还有个办法就是用 context 带下去。。。

**Comment by jljsj33** [comment]
### pages/index.tsx
```jsx
import styles from './index.less';
import { Button } from 'antd';
import { history } from 'umi';
import React, {  createContext } from 'react';
import { withRouter, Switch } from 'umi';
import { TweenOneGroup } from 'rc-tween-one';

const animate = {
  enter: { x: '100vw', duration: 1000, ease: 'easeInOutCubic' },
  leave: { x: '100vw', duration: 1000, ease: 'easeInOutCubic' },
};

export const TestContext = createContext(null);

const Child = React.forwardRef(({ location, children }, ref) => {
  return (
    <div className="layout-anim-child" ref={ref}>
      <TestContext.Provider value={location}>
        <Switch location={location}>{children}</Switch>
      </TestContext.Provider>
    </div>
  );
});

export default withRouter(({ children, location }) => {
  const { pathname } = location;
  const pathArray = pathname.split('.')[0].split('/');
  const path = pathArray[pathArray.length - 1];
  const key = path || 'index';
  const enter = key === 'index' ? animate.leave : animate.enter;
  const leave = key === 'index' ? animate.enter : animate.leave;
  return (
    <div>
      <Button onClick={() => {history.push('/page1')}} type="primary">
        page1
      </Button>
      <Button onClick={() => {history.push('/page2')}}>page2</Button>
      <TweenOneGroup
        enter={[
          { type: 'set', zIndex: key === 'index' ? 0 : 1 },
          { ...enter, type: 'from' },
        ]}
        leave={[{ type: 'set', zIndex: key === 'index' ? 1 : 0 }, leave]}
        appear={false}
        className="app-layout"
      >
        <Child
          key={key}
          location={location}
         >
           {children.props.children}
        </Child>
      </TweenOneGroup>
    </div>
  );
});

```
### layouts/index.jsx
```jsx
import React, {  useContext } from 'react';
import { withRouter, Switch, useLocation } from 'umi';
import { TestContext } from '../pages/index';

export default withRouter(({ children, ...props }) => {
  const location = useContext(TestContext);

  return (
    <div style={{ position: 'absolute', width: '100%' }}>
      {location.pathname}
      <Switch location={location}>{children.props.children}</Switch>
    </div>
  );
});
```

**Comment by wansuiasdn** [comment]
谢谢谢谢，学习了！ 
![image](https://user-images.githubusercontent.com/47979542/106729910-f6d89680-6648-11eb-9c03-0baac6191917.png)

**Comment by wansuiasdn** [comment]
@jljsj33 大佬，我还有个问题，就是location是随路由跳转即时更新的，请问是TweenOneGroup这个组件帮忙做的缓存，然后滞后更新的么

**Comment by jljsj33** [comment]
所有类似的动画组件都是在内部管理元素变更的状态的，在组件内部 state 里保存 children，切换时将上一个 children 做一个出场，然后新的 children 做进场...

**Comment by wansuiasdn** [comment]
@jljsj33 谢谢您，了然，给您跪了
![image](https://user-images.githubusercontent.com/47979542/106842404-f12d9000-66de-11eb-90cc-ab0e9d90d12a.png)
