### ISSUE TITLE
help

### ISSUE THREAD

**Issue by oqq5518** [ant-design/ant-motion#33]
![image](https://cloud.githubusercontent.com/assets/4516065/20658636/4b6bfabe-b579-11e6-84cf-2d882c9fdf7f.png)

![image](https://cloud.githubusercontent.com/assets/4516065/20658658/5d1dee2a-b579-11e6-83f9-e03f3bb65c54.png)

**Comment by jljsj33** [comment]
代码发我邮箱，，我看看吧。。。

**Comment by oqq5518** [comment]
已发

**Comment by jljsj33** [comment]
你升级下你的依赖版本。。。汗。。。。。。

**Comment by jljsj33** [comment]
```
   "rc-banner-anim": "~0.5.4",
    "rc-queue-anim": "~0.12.0",
    "rc-scroll-anim": "~0.5.3",
    "rc-tween-one": "~0.11.9",
```

**Comment by jljsj33** [comment]
我那文档没改，，汗。。。。

**Comment by jljsj33** [comment]
还有你没用 css-modules， 那个 :global{}不需要加

**Comment by jljsj33** [comment]
你这样排序如果导航出不来，，样式上加个 top: 0

**Comment by oqq5518** [comment]
![image](https://cloud.githubusercontent.com/assets/4516065/20659817/ec9eb014-b580-11e6-97ed-4d9a6f566996.png)
footer怎么上移了..

**Comment by jljsj33** [comment]
。。。。。你在index.jsx里调整顺序啊

**Comment by jljsj33** [comment]
```
export default class Home extends React.Component {
  render() {
    const children = [
      <Nav0 key="nav_0_2" name="nav_0_2" {...props[1]} />,
      <Banner1 key="banner_1_1" name="banner_1_1" {...props[0]} />,
      <Content4 key="content_4_4" name="content_4_4" {...props[3]} />,
      <Content4 key="content_4_5" name="content_4_5" {...props[4]} />,
      <Footer1 key="footer_1_3" name="footer_1_3" {...props[2]} />,
    ];
    return (
      <div className="templates-wrapper">
        {children}
      </div>
    );
  }
}
```

不用点把 componentDidMount 去掉

**Comment by oqq5518** [comment]
刚刚调了 报错 现在可以了 现在没加top:0...我是在qcon上看到你们介绍ant-design的😆

**Comment by jljsj33** [comment]
哦，，如果对 motion 有啥建议或感受，可以在 https://github.com/ant-design/ant-motion/issues/30 里写下
