### ISSUE TITLE
Animate组件对于Table的增删的离场动效

### ISSUE THREAD

**Issue by zuiidea** [ant-design/ant-motion#34]
如果只对一两行操作很完美。
![gif2](https://cloud.githubusercontent.com/assets/16070518/20788223/d09d5b42-b7ea-11e6-9a3e-a11423d89752.gif)

当进行切换页的时候，上一页的元素dom元素还在，会撑开整个table，很难看
![gif1](https://cloud.githubusercontent.com/assets/16070518/20788225/d1f573e4-b7ea-11e6-9fd9-2c0867b34308.gif)

如果设置transitionLeave=false，就没有离场动效了

so,怎么样才能更优雅

**Comment by jljsj33** [comment]
https://motion.ant.design/exhibition/demo/table-enter-leave 
如果要效果，可以把看下这个。。

用 css 的暂时还没方案。。。

**Comment by zuiidea** [comment]
@jljsj33，用了这个方案https://motion.ant.design/exhibition/demo/table-enter-leave，这css写法略显丑陋啊，这会出现一些小bug，
1.单元格文字过长，出现换行时，这时候高度会发生变化，切页的时候，pagination会发生抖动，
2.当每页切换20条，甚至40条时，切页时显示会变得很慢，这可能跟pageChange时，修改的动画参数有关
![image](https://cloud.githubusercontent.com/assets/16070518/20825008/33dc5f8a-b89c-11e6-9e49-b04672512746.png)

**Comment by jljsj33** [comment]
pagination 会拦动？？？？不是滑动的？？？

**Comment by jljsj33** [comment]
切换时页面变慢我看下能不用就在 tbody 上，

**Comment by afc163** [comment]
https://motion.ant.design/exhibition/demo/table-enter-leave

在 Firefox 新增删除行为都很怪异。

**Comment by jljsj33** [comment]
@afc163 你的 fireFox 可以卸了，，，重装

**Comment by zuiidea** [comment]
![gif3](https://cloud.githubusercontent.com/assets/16070518/20826490/3e4d1d7e-b8a6-11e6-9102-36246cc36179.gif)

动画参数和官网示例上是一样的，另外在官网上没找到timeline的说明，所以我尝试稍微修改参数，切页动画就会很怪异，离场效果浪费了很多时间，在每页条数更多的时候会更明显，讲道理应该是整块执行一次离场，这样弄得每一条都有一个离场，且是同步的
![image](https://cloud.githubusercontent.com/assets/16070518/20826516/7541c55a-b8a6-11e6-9dd0-22ddae2ed67f.png)

**Comment by jljsj33** [comment]
timeline就是数组的对象，[{ opacity: 1}, { x: 100}]为timeline,,,,,看tweenone的

**Comment by jljsj33** [comment]
没加appearTo，是播放完前面的对象后再播放后面的，，依次播放

**Comment by jljsj33** [comment]
如果卡，翻页的动画去掉吧。。。。。有点坑。。。

**Comment by jljsj33** [comment]
改动的地方:

```jsx
constructor(props){
   this.currentPage = 1;
   this.newPage = 1;
}
getBodyWrapper = body => {
    if (this.currentPage !== this.newPage) {
      this.currentPage = this.newPage;
      return body;
    }
    return (<TweenOneGroup
      component="tbody"
      className={body.props.className}
      enter={this.enterAnim}
      leave={this.leaveAnim}
      appear={false}
    >
      {body.props.children}
    </TweenOneGroup>);
  }


  pageChange = (pagination) => {
    this.newPage = pagination.current;
  };
```

**Comment by jljsj33** [comment]
这样写用 rc-animate 好像也可以的。。。

**Comment by zuiidea** [comment]
啊，毕竟没翻页动画了。。。。

**Comment by jljsj33** [comment]
恩，翻页毕竟还有个 load 在啊，，所以翻页的动画感觉没什么必要。。。可以去掉。。再说在 table 下，插个元素太难了。。。。一行一个动画又太卡。。。。

**Comment by zuiidea** [comment]
刚刚那段代码并没有什么用，离场的那一页已经绑定了动画了

**Comment by jljsj33** [comment]
你看下线上的 https://motion.ant.design/exhibition/demo/table-enter-leave ，
我发上去了

**Comment by zuiidea** [comment]
@jljsj33 我复制了线上demo的是可以的，但是我这里又出现问题了。

![gif5](https://cloud.githubusercontent.com/assets/16070518/20872272/24930b4e-bad8-11e6-8123-7b759c2c30c4.gif)

这里是异步获取的数据，页面change时会改state,导致重新render table，getBodyWrapper就会执行多次，用页面判断就没用了

下面是页面change时代码

```bash
  handleTableChange(pagination, filters, sorter){
    const pager = this.state.pagination
    pager.current = pagination.current
    this.newPage = pagination.current
    pager.offset = (pagination.current - 1) * pagination.pageSize
    pager.pageSize = pagination.pageSize
    this.fetch()
  },
  fetch(options){
    const _this = this
    const pagination = {
      offset: _this.state.pagination.offset,
      max: _this.state.pagination.pageSize,
    }
    if(!options||(options&&options.loading)){
      _this.setState({
       ..._this.state,
       loading: true,
      })
    }
    Ajax({
      url:contextPath+'/order/index',
      data:{
        ...pagination,
        ...this.state.params,
      },
      success:function(result){
         _this.setState({
          ..._this.state,
          data: result.orderList,
          pagination:{
            ..._this.state.pagination,
            total: result.total
          },
        })
      },
      complete:function(){
        _this.setState({
         ..._this.state,
         loading: false,
        })
      }
    })
  },
```

**Comment by jljsj33** [comment]
appear={false} 设了吗？？？？

**Comment by zuiidea** [comment]
有的，跟demo上一样的

**Comment by jljsj33** [comment]
那你试试把 this.newPage = current 移到 complete 里？
```jsx
handleTableChange(pagination, filters, sorter){
    const pager = this.state.pagination;
    pager.current = pagination.current;
    pager.offset = (pagination.current - 1) * pagination.pageSize;
    pager.pageSize = pagination.pageSize;
    this.fetch(null, pager.current);
  },
  fetch(options, current){
    const _this = this;
    const pagination = {
      offset: _this.state.pagination.offset,
      max: _this.state.pagination.pageSize,
    };
    if(!options||(options&&options.loading)){
      _this.setState({
       ..._this.state,
       loading: true,
      });
    }
    Ajax({
      url:contextPath+'/order/index',
      data:{
        ...pagination,
        ...this.state.params,
      },
      success:function(result){
         _this.setState({
          ..._this.state,
          data: result.orderList,
          pagination:{
            ..._this.state.pagination,
            total: result.total
          },
        })
      },
      complete:function(){
        _this.newPage = current;
        _this.setState({
         ..._this.state,
         loading: false,
        });
      }
    })
  },
```

**Comment by zuiidea** [comment]
@jljsj33,perfetc，thx
