### ISSUE TITLE
overPack

### ISSUE THREAD

**Issue by Ai01** [ant-design/ant-motion#35]
overPack设置了在屏幕下方 50％ 时开始播放动画，希望可以有屏幕上半部分的‘overPack’。

**Comment by jljsj33** [comment]
出场播放吗？？？

**Comment by jljsj33** [comment]
playScale	number / array	0.5	要在屏幕哪个区域开始播放， 0.5 为屏幕中间, 如果为 array 时 replay 为 true, [bottom-enter, top-leave] enter为进入是的播放点， topLeave 为出屏的比例(当前显示屏的上面一屏)的百分点。topLeave 必须大于等于 bottomEnter。

**Comment by Ai01** [comment]
谢谢了。我没注意到overPatch继承了playScale
