### ISSUE TITLE
请教下，怎么跟 react-router 结合做动效？

### ISSUE THREAD

**Issue by 285858315** [ant-design/ant-motion#36]
给个简单的示例就好。

**Comment by jljsj33** [comment]
如果用的是 bisheng, 直接拉master 分支就是很好的demo..... 不用 bisheng 可以切到1.0.1分支。。。。
看这个：https://github.com/ant-design/ant-motion/blob/1.0.1/src/entry/index.jsx

**Comment by jljsj33** [comment]
queueAnim 的 router demo http://react-component.github.io/queue-anim/examples/router.html

**Comment by 285858315** [comment]
多谢，我去试试。
