### ISSUE TITLE
OverPack 组件在TS文件下的自带 always属性不存在

### ISSUE THREAD

**Issue by panpeng0014** [ant-design/ant-motion#377]
Overload 1 of 2, '(props: Readonly<IProps<IProps>>): RcScrollOverPack', gave the following error.
    Type '{ children: Element; location: string; always: boolean; playScale: string; className: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<RcScrollOverPack> & Readonly<IProps<IProps>> & Readonly<...>'.
      Property 'always' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RcScrollOverPack> & Readonly<IProps<IProps>> & Readonly<...>'.
  Overload 2 of 2, '(props: IProps<IProps>, context?: any): RcScrollOverPack', gave the following error.
    Type '{ children: Element; location: string; always: boolean; playScale: string; className: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<RcScrollOverPack> & Readonly<IProps<IProps>> & Readonly<...>'.
      Property 'always' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RcScrollOverPack> & Readonly<IProps<IProps>> & Readonly<...>'.
    53 |             <div id='case' className='cases'>
    54 |                 <div className='cases-title'>经典案例展示</div>
  > 55 |                 <OverPack location='case' always={false} playScale='0.4' className='cases-area'>
       |                                           ^
    56 |                     <RcQueueAnim key='titleQueue' className='cases-area-queue' component='ul' duration={500}
    57 |                         ease={['easeOutQuart', 'easeInOutQuart']}
    58 |                         animConfig={[{ opacity: [1, 0], translateY: [0, 100] }]}>

> Build error occurred

**Comment by jljsj33** [comment]
https://github.com/react-component/scroll-anim/blob/master/src/ScrollOverPack.d.ts#L5, 有写着啊，，，看下你的依赖？？？

**Comment by Lzleaf** [comment]
> https://github.com/react-component/scroll-anim/blob/master/src/ScrollOverPack.d.ts#L5, 有写着啊，，，看下你的依赖？？？

依赖里面是有, 但是使用上好像有问题,  Parallax 使用 always 就没问题, 用 OverPack 会有报错, 不存在属性“always”
`export const Element: typeof ScrollElement;
export const OverPack: typeof ScrollOverPack;
export const Parallax: typeof ScrollParallax;
export const Link: typeof ScrollLink;
export const scrollScreen: typeof Screen;
export const Event: typeof ScrollEvent;

declare const ScrollAnim: {
  Element: typeof ScrollElement,
  OverPack: typeof ScrollOverPack,
  Parallax: typeof ScrollOverPack,
  Link: typeof ScrollLink,
  scrollScreen: typeof Screen,
  Event: typeof ScrollEvent,
}

export default ScrollAnim;`

使用 ScrollAnim.OverPack / ScrollAnim.Parallax 都是无法使用 always 的,  
`export const Parallax: typeof ScrollParallax;`

使用这个 Parallax 可以正常用 always 属性. 不清楚什么原因
大神能帮忙看下吗

**Comment by 17862974826** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
