### ISSUE TITLE
SVG 线性动画 在IE11下崩溃

### ISSUE THREAD

**Issue by river-hu** [ant-design/ant-motion#398]
![image](https://user-images.githubusercontent.com/30434057/92449269-6195bb00-f1ec-11ea-8095-764dc6367f74.png)
一直提示这个错误，导致页面崩溃

`import SvgDrawPlugin from 'rc-tween-one/lib/plugin/SvgDrawPlugin';
import TweenOne from 'rc-tween-one';
TweenOne.plugins.push(SvgDrawPlugin);`

`  <svg width="100%" height="100%"  version="1.1"
                            xmlns="http://www.w3.org/2000/svg">
         <TweenOne
                                        animation={[ { SVGDraw: 0, duration: 0 }, { SVGDraw: "100%", duration: 1000 }]}
                                            style={{ fill: 'none', strokeWidth: 1, stroke: '#000' }}
                                            component="path"
                                            d="M459 254 V176 H200 "
                                        />
 </svg>
`

**Comment by river-hu** [comment]
qq与360兼容模式下的ie11，ie edge模拟下的ie11没有问题

**Comment by jljsj33** [comment]
这报错跟 tween-one 有半点关系吗？？
