### ISSUE TITLE
不好意思歪个楼,动效模板里面的颜色选择器是用的哪个插件?

### ISSUE THREAD

**Issue by xd199153** [ant-design/ant-motion#40]
看着挺好看,-_-.
谢谢.

**Comment by xd199153** [comment]
https://motion.ant.design/edit#t%3Dnav_0_0%2Ccontent_0_0%2Ccontent_2_0%2Ccontent_3_0%2Ccontent_4_0%2Cfooter_0_0

**Comment by jljsj33** [comment]
挺歪的。。。哈哈 https://github.com/casesandberg/react-color

**Comment by xd199153** [comment]
非常感谢
