### ISSUE TITLE
scrollScreen会连续滚动多页

### ISSUE THREAD

**Issue by wanghuan1115** [ant-design/ant-motion#43]
在使用scrollScreen进行滚动翻页时，由于鼠标或触控板的滚动时间长于scrollInterval的设定时间时，会发生连续滚动多页的情况，即使在默认值1000时依然会有这种现象发生，而实际1000已经是很长的一段时间了，能不能锁定一次只能滚动一页，不管一次滚动持续了多久？望告知，谢谢。

**Comment by jljsj33** [comment]
这个应该不影响吧。。。如果你持续在滑板上滑动，，那么在间隔的时间里你页面已经呈现完成了，，自然是继续滚动了。。。以前也想过，，一般在浏览网页的情况下你手放在触控板上是不愿离开，如果不继续滚，，那么他要往下滚时，，要释放滑板再一次去触碰滑板才继续滚动，，这样体验不好。。。

**Comment by wanghuan1115** [comment]
抱歉可能没有描述清楚，并不是持续在人为操作滑动，而是因为一定时间的惯性导致滚动在持续，比如mac的触摸板进行一次从底部滑到顶部的操作松手，或者鼠标滚动惯性较大的（比如我用的arc touch），两种情况都会触发两次翻页，如果间隔时间短，甚至出现3、4、5次翻页。作为用户第一反应是我只滑动了一次，为何给我翻动多页呢？
考虑项目上线时间要求已经放弃scrollScreen方案，但未免以后还会有此类需求，希望在后续更新中能够提供一个开关进行限制翻页判断，谢谢。

**Comment by jljsj33** [comment]
你这需求间隔时间设长应该就可以了
