### ISSUE TITLE
tweenOne为什么没有onEnd

### ISSUE THREAD

**Issue by Aszzo** [ant-design/ant-motion#46]

**Comment by jljsj33** [comment]
.... onChange(e)。。。e.mode === 'onComplete' 就是结束。。。
```jsx
onChange = (e) => {
  if(e.mode === 'onComplete'){
  //结束
}
}
<TweenOne onChange={onChange} animation={{ x: 100 }}/>
```

或者

```jsx
<TweenOne animation={{ x: 100, onComplete: onChange }} />
```

**Comment by Aszzo** [comment]
同一个对象有mouseenter跟mouseleave两个事件，我想在mouseleave的complete的时候执行操作。这样onComplete会有好几次

**Comment by Aszzo** [comment]
我一开始想到过onChange，而且也打印了e的所有属性，=.=

**Comment by jljsj33** [comment]
不懂。。。。提供下代码

**Comment by Aszzo** [comment]
没事了..用<TweenOne animation={{ x: 100, onComplete: onChange }} />这个解决了。官网api里面animation里没有onComplete                https://motion.ant.design/api/tween-one

**Comment by zhouzefei** [comment]
![image](https://cloud.githubusercontent.com/assets/8566935/23595994/7522cc4a-0261-11e7-8b4e-ce9fd1f6700c.png)
提个建议，还有移动端呢！如果没有直接写style，还是用style.cssText="none";
