### ISSUE TITLE
https://motion.ant.design中的动效模板无法生成代码

### ISSUE THREAD

**Issue by hongqp** [ant-design/ant-motion#49]
https://motion.ant.design
网站上，点击进入“动效模板”后，点击生成代码，无任何响应（应该生成一个文件并启动下载吧？）
后者应该如何进行操作才能给导出模板代码呢？

浏览器版本：
firefox51.0.1（32位）

**Comment by jljsj33** [comment]
好的，有个报错，，我看下，，，暂时先用 chrome 下载吧。。。

**Comment by MincoTse** [comment]
动态模板生成完代码，不知道怎么用。能不能直接一步到位 生产成代码 为JS html 呢？

**Comment by jljsj33** [comment]
这个我也没办法，去看下 react 再看下我的说明文档吧。。https://github.com/ant-design/ant-motion/blob/master/src/templates/template/other/documentation.text。。。。还有不要在别人的 issuse 里提问。。。
