### ISSUE TITLE
npm start报错，求解

### ISSUE THREAD

**Issue by NONGFUER** [ant-design/ant-motion#50]
![image](https://cloud.githubusercontent.com/assets/20360093/22919295/fd71cc7e-f2c9-11e6-8b1c-397a0b06e3c1.png)
![image](https://cloud.githubusercontent.com/assets/20360093/22919310/15da8a6c-f2ca-11e6-9f01-d4ded731708e.png)

**Comment by jljsj33** [comment]
npm i 了没?

**Comment by jljsj33** [comment]
![image](https://cloud.githubusercontent.com/assets/6802825/22919956/9bf05886-f2cd-11e6-81ae-8d37c0ffeb7b.png)
改成 ~0.13.0

**Comment by NONGFUER** [comment]
我有npm install,按你的方法改成~0.13.0，将原来的删了重新npm install了遍。但还是报原来的错。为什么
![image](https://cloud.githubusercontent.com/assets/20360093/22921083/361f6a14-f2d3-11e6-8e2b-ddd88a5809bc.png)路径分割符没了

**Comment by jljsj33** [comment]
npm 和 node 版本是什么？？？

**Comment by NONGFUER** [comment]
![image](https://cloud.githubusercontent.com/assets/20360093/22921770/f5034cd2-f2d5-11e6-81f0-26b21c67dfac.png)

**Comment by jljsj33** [comment]
好吧，，是 bisheng 不支持 window。。。没解了。。。

**Comment by jljsj33** [comment]
等  bisheng 发 1.0.0 后再做升级。。。。
https://github.com/benjycui/bisheng/issues/35

**Comment by NONGFUER** [comment]
我antd-design启动没问题，但除了首页，其他都是404，也是这原因吗

**Comment by jljsj33** [comment]
ant-d 的应该没这个问题。
