### ISSUE TITLE
遮盖问题

### ISSUE THREAD

**Issue by spiroo** [ant-design/ant-motion#51]
![image](https://cloud.githubusercontent.com/assets/7858201/23052591/78eb47fa-f50d-11e6-9e80-255e72b4c8ab.png)

下边的div会遮盖住Menu的二级菜单，如：
![image](https://cloud.githubusercontent.com/assets/7858201/23052538/0e438aa2-f50d-11e6-85ab-bdee353d195e.png)

正常的情况应该是：
![image](https://cloud.githubusercontent.com/assets/7858201/23052549/2207f80c-f50d-11e6-80d9-5ea4bc2d96de.png)

**Comment by jljsj33** [comment]
？？？你把 div 的 zindex 设高一层就可以啊。。

**Comment by spiroo** [comment]
@jljsj33 div已经盖住menu了，还要设高一层？

我改过menu的z-index，不起作用

**Comment by jljsj33** [comment]
queue-anim 没有改变你的 zindex，，你仔细检查一下。。。或提供下代码

**Comment by jljsj33** [comment]
ant-d 的 subMenu zIndex 是 1050, 你看下你的 div 的 zIndex

**Comment by spiroo** [comment]
确实没有改变z-index，但我div也没设置z-index啊，确实是遮盖了

**Comment by jljsj33** [comment]
<Menu /> 外面加个 div 试试

```jsx
<QueueAnim>
  <div key="0"><Menu /></div>
  <div key="1" />
</QueueAnim>
```

**Comment by spiroo** [comment]
![image](https://cloud.githubusercontent.com/assets/7858201/23054342/585b4028-f51a-11e6-96d0-ab466d693b89.png)

加上也不行

另外，怎么加code呀，我加上怎么是在一行显示的
`<QueueAnim delay={500} className="queue-simple">
        <div key="a">
          <Header {...headerProps} />
        </div>
        <div className={styles.menu} key="b">
          <MainMenu {...menuProps} />
        </div>
        <div key="c" className={styles.main}>
          {children}
        </div>
      </QueueAnim>`

**Comment by jljsj33** [comment]
。。。。https://segmentfault.com/markdown

**Comment by spiroo** [comment]
```javascript

      <QueueAnim delay={500} className="queue-simple">
        <div key="a">
          <Header {...headerProps} />
        </div>
        <div className={styles.menu} key="b">
          <MainMenu {...menuProps} />
        </div>
        <div key="c" className={styles.main}>
          {children}
        </div>
      </QueueAnim>
```

会了。。。

**Comment by jljsj33** [comment]
把 QueueAnim 改成 div 看看是不是也遮住，遮住了，，你用 chrome  审核下元素看看他的样式的 zIndex....

**Comment by jljsj33** [comment]
这用 jsx

**Comment by spiroo** [comment]
@jljsj33 jsx？

QueueAnim改成div或者去掉QueueAnim标签，就可以正常显示

**Comment by jljsj33** [comment]
提供下代码，，我看看。。。

**Comment by spiroo** [comment]
我怎么给你呢？

**Comment by jljsj33** [comment]
155259966@qq.com

**Comment by spiroo** [comment]
@jljsj33 
我做了个demo，github地址为：git@github.com:spiroo/QueueAnimTest.git，请指教！

**Comment by jljsj33** [comment]
transform 的问题。。。 两个解决方案：

1. 在动画结赖后把 transform 设回 none; 可参考 https://github.com/ant-design/ant-design/issues/3088#issuecomment-248271710,,,[ ant motion 的实现](https://github.com/ant-design/ant-motion/blob/master/src/theme/template/Layout/index.jsx#L18)

2. 在 menu 样式里加上
```css
.menu {
  width: 1000px;
  margin: 0 auto 50px;
  position: relative;
  z-index: 1050;
}
```

**Comment by spiroo** [comment]
@jljsj33 非常感谢
