### ISSUE TITLE
ListSort.jsx中getChildren的ref丢失了

### ISSUE THREAD

**Issue by flybird1** [ant-design/ant-motion#512]
getChildren = (item, i) => {
    const onMouseDown = this.onMouseDown.bind(this, i);
    const style = { ...this.state.childStyle[i] };
    return React.createElement(
      TweenOne,
      {
        ...item.props,
        **ref: item.ref,**
        onMouseDown,
        onTouchStart: onMouseDown,
        style: { ...item.style, ...style },
        key: item.key,
        animation: this.state.animation[i],
        component: item.type,
      }
    );

**Comment by jljsj33** [comment]
不维护了，，可以考虑使用这个，https://github.com/clauderic/dnd-kit
