### ISSUE TITLE
在nextjs中使用提示 Warning: Did not expect server HTML to contain a <div> in <div>.

### ISSUE THREAD

**Issue by hjyyang** [ant-design/ant-motion#513]
直接复制的官方demo在nextjs中使用提示  Warning: Did not expect server HTML to contain a <div> in <div>.
![image](https://user-images.githubusercontent.com/31732570/158403388-4468e62b-6ded-4eee-82bd-9db162993b60.png)
终端报错信息：
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

**Comment by jljsj33** [comment]
Warning 不管

**Comment by jljsj33** [comment]
https://github.com/react-component/tween-one/pull/132

**Comment by SmileABC** [comment]
![image](https://user-images.githubusercontent.com/32155895/182754255-47262608-dec6-4778-89a1-7e6b20277f41.png)
![image](https://user-images.githubusercontent.com/32155895/182754112-c6d9a358-4f06-402d-851d-a4480dbc8fb5.png)
我的解决方案给你参考一下，希望可以帮到你
