### ISSUE TITLE
TweenOne TS类型错误

### ISSUE THREAD

**Issue by asdyin142** [ant-design/ant-motion#516]
文档支持Boolean,但是在ts中不支持Boolean,导致ts报错
![image](https://user-images.githubusercontent.com/52064574/168513571-c4270811-d63a-47e5-97d7-d7d62f3d9c1c.png)
![image](https://user-images.githubusercontent.com/52064574/168513604-37f69b73-d778-4ba7-a1d7-55c0207bf0e6.png)

**Comment by jljsj33** [comment]
那就忽略 boolean 类形吧，，用 { thousand: ',', decimal: '.' }
