### ISSUE TITLE
rc-banner-anim ^2.4.5 版本的 BannerAnim 组件的 bug

### ISSUE THREAD

**Issue by ayangweb** [ant-design/ant-motion#522]
当 BannerAnim 组件的 type 为 gridBar 时，在切换过程中，前一张背景上面的文字忽然闪了一下然后跟随消失，而并不是官网所示的效果！为了避免是我项目引起的问题，我开了一个全新的项目，然后把官网的案例一模一样的搬了上去，啥都没改，项目启动后仍然会出现这个问题！下面附上一份演示视频，以供参考！

https://user-images.githubusercontent.com/75017711/202137310-2dcf8d1a-de68-42fc-8d1f-b595ae851fdd.mp4

**Comment by 17862974826** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 17862974826** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
