### ISSUE TITLE
Sidebar hiding by the footer

### ISSUE THREAD

**Issue by Sudan08** [ant-design/ant-motion#525]
![image](https://github.com/ant-design/ant-motion/assets/96038386/c06b2538-4f0d-408e-b6e8-56cf5986a5d2)
The parallex effect seems to not work properly

**Comment by 17862974826** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Sudan08** [comment]
This issue already exists sorry!!
