### ISSUE TITLE
动效模板更换背景图片无法生效

### ISSUE THREAD

**Issue by himyspace** [ant-design/ant-motion#55]
动效模板更换背景图片无法生效
视频教程中有保存按钮，但是网页上没有，其他的参数设置后，效果生效，但是背景图片更改后，不起作用。
经过测试需要修改为:url(图片地址)才可以

**Comment by jljsj33** [comment]
哪个模板？

**Comment by jljsj33** [comment]
视频是旧版，，没更新

**Comment by jljsj33** [comment]
看到了，，content0 为了适配手机的 fixed ，，所以加在before 里，，所以导至出错。。。
