### ISSUE TITLE
animation queue 的 api 文档一个参数有误

### ISSUE THREAD

**Issue by ChinaXing** [ant-design/ant-motion#57]
https://motion.ant.design/api/queue-anim

component 参数的类型文档中写的是string， 其实可以是ReactDom。

亲测 component={Row} 可用

**Comment by jljsj33** [comment]
谢谢，本来就可以用的，，是 Row 还能跑起来， 但如 table 之类的是跑不起来的，所以这块是没法控制的，要看组件是怎么样写的。。。所兴就不建议这么使用，直接就写成 string。。。
