### ISSUE TITLE
表格信息删除动画中，当表格存在输入框内容时，会出现内容变化的问题

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-motion#63]
在一个表格中，如果存在有输入框，并且输入框内有内容的时候，如下图
![1](https://cloud.githubusercontent.com/assets/7866330/24037033/2e673988-0b37-11e7-851c-36c8418246d9.png)

这个时候操作删除数据的操作，输入框的内容就会先变化，然后再执行删除的动画效果。如下图，输入框内的数字会全部先变为0，然后再是leave的动画。
![2](https://cloud.githubusercontent.com/assets/7866330/24037071/5b03f7b0-0b37-11e7-920c-6b68f27e8f27.png)

**Comment by jljsj33** [comment]
key是固定的吗？？？提 供下代码吧。。。

**Comment by jljsj33** [comment]
http://codepen.io/jljsj33/pen/RpjQvw

**Comment by buxuku** [comment]
通过排查，是因为自己的input是动态取值的，因为在取值过程中出现了问题，不是因为动画引起的，非常抱歉了。可以关闭此issue了。
