### ISSUE TITLE
依赖不存在？

### ISSUE THREAD

**Issue by wuyongdec** [ant-design/ant-motion#64]
通过快速搭建创建的demo,文档里面的依赖不存在？
![image](https://cloud.githubusercontent.com/assets/7280016/24087205/0751dba6-0d57-11e7-9ecd-2a11c3bf9d72.png)

**Comment by jljsj33** [comment]
??????  cnpm 上有啊，，，https://cnpmjs.org/package/rc-tween-one。。。。

升级下版本看看。。。

**Comment by wuyongdec** [comment]
@jljsj33 我按照文档来添加的，貌似不依赖也没有问题 ， rc-tween-one 有

**Comment by afc163** [comment]
https://github.com/ant-design/ant-motion/blob/e9934a6a157cfca02900967eeaff21a6b57195ae/src/templates/template/other/documentation.text#L26

**Comment by jljsj33** [comment]
额。。。。好吧。。。。谢谢。。。。

**Comment by jljsj33** [comment]
dva-cli 一般都自动装了的。。。可以忽略。。。
