### ISSUE TITLE
css问题

### ISSUE THREAD

**Issue by ntfs32** [ant-design/ant-motion#65]
错误:
Failed to compile.

Error in ./src/routes/home/less/antMotion_style.less
Module not found: 'edit.css' in /home/shaddock/Applications/htdocs/MyDMP2.0/src/routes/home/less

 @ ./~/css-loader?importLoaders=1&modules&localIdentName=[local]___[hash:base64:5]!./~/postcss-loader!./~/less-loader?{"modifyVars":{}}!./src/routes/home/less/antMotion_style.less 3:10-190

请问这个怎么解决呢

**Comment by jljsj33** [comment]
???提供下详细步骤。。。。是在 dva-cli 下的吗，，什么开发工具?

**Comment by ntfs32** [comment]
@jljsj33 解决了 谢谢 需要把 antMotion_style.less 里面global 还有 edit.css 不太行，会有问题 也改less了

那个整屏向下滚动有些问题，我再试试。。。

**Comment by jljsj33** [comment]
https://github.com/ant-motion/ant-motion-dva-cli-example/tree/master
