### ISSUE TITLE
rc-tween-one 依赖缺失问题

### ISSUE THREAD

**Issue by liSong5713** [ant-design/ant-motion#66]
in ./~/rc-tween-one/~/deep-eql/index.js
Module build failed: Error: ENOENT: no such file or directory, open '
**/node_modules/rc-tween-one/node_modules/deep-eql/index.js'
 @ ./~/rc-tween-one/lib/util.js 26:15-34

**Comment by jljsj33** [comment]
npm install tween-one --save 了没？？？

提供下具体情况。。。。这样看不懂。。。

**Comment by jljsj33** [comment]
没反应，关闭
