### ISSUE TITLE
roadhog打包无法打包less

### ISSUE THREAD

**Issue by YunS-Stacy** [ant-design/ant-motion#67]
运行roadhog build 后页面没有包括由less生成的样式

**Comment by zuiidea** [comment]
roadhog默认使用了css module

**Comment by jljsj33** [comment]
先请不要使用 css-modules, 将在下个版本做混用兼容；
 在 .roadhogrc 文件里加上: "disableCSSModules": true,

https://github.com/ant-design/ant-motion/blob/master/src/templates/template/other/documentation.text#L9

**Comment by YunS-Stacy** [comment]
我已经加上了，可是还是不行

**Comment by jljsj33** [comment]
没问题啊。。。。

.roadhogrc 文件是这样的
```
{
  "entry": "src/index.js",
  "disableCSSModules": true,
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime"
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ]
    }
  },
  "extraBabelPlugins": [
    "transform-runtime",
    ["import", { "libraryName": "antd", "style": true }]
  ]
}

```

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-motion/blob/master/src/templates/template/other/documentation.text 这文件的步骤一步一步下来。。。

**Comment by jljsj33** [comment]
搞了个例子，，你看下吧。。。https://github.com/ant-motion/ant-motion-dva-cli-example/tree/master

**Comment by zuiidea** [comment]
吐槽一下动效模板里的less写得很一般...改着心累

**Comment by jljsj33** [comment]
怎么了。。挺久前写的模板。。懒得改了。。你可以pr来改下啊。。哈哈哈

**Comment by jljsj33** [comment]
很久前模板和网站的样式是合并着的。。后面没分离。。所以有点乱。。。
