### ISSUE TITLE
banner

### ISSUE THREAD

**Issue by taohailin** [ant-design/ant-motion#69]
banner 的子元素是absolute,如果banner的高度需要子元素来撑的话，就不行了

**Comment by jljsj33** [comment]
banner 还要子元素去撑高？？？不建议吧。。没碰到这种情况，，一般情况下 banner 里的元素都是固定的，所以 banner 高度一般都是固定的或 100vh 吧。。。如果有这种强制需求，，你设个 min-height 再把子级样式替换掉吧。。。
