### ISSUE TITLE
banner动画问题

### ISSUE THREAD

**Issue by zidoshare** [ant-design/ant-motion#71]
我使用动效模板生成的代码，在本地使用时切换动画时，两张没有任何衔接，甚至有时候点切换没有动画，直接卡住的感觉

对比：

原版：

![原版](http://odp22tnw6.bkt.clouddn.com/origin.gif)

我的：

![我的](http://odp22tnw6.bkt.clouddn.com/me.gif)

**Comment by jljsj33** [comment]
升级下tweenOne

**Comment by jljsj33** [comment]
~1.1.5

**Comment by zidoshare** [comment]
我就是这个版本的

^1.1.5

**Comment by jljsj33** [comment]
明天我看下，，你选择的是哪几个模板？？？

**Comment by zidoshare** [comment]
我就只是单独选了个banner，我开始选择的是单张背景的，后来想换成多个背景的

**Comment by jljsj33** [comment]
依赖全删了，，重装下看看`rm -rf node_modules/ && npm install `

**Comment by jljsj33** [comment]
我本地测了没问..

**Comment by zidoshare** [comment]
我已经全部删除了，要不你帮我看看下代码？我存在github上了
https://github.com/zidoshare/react-starter/blob/master/src/components/Nav/Nav.js

**Comment by zidoshare** [comment]
发错了，是这个
https://github.com/zidoshare/react-starter/blob/master/src/components/Home/Content0.jsx

**Comment by jljsj33** [comment]
好的。。明天我看下。。

**Comment by zidoshare** [comment]
恩恩，谢谢，麻烦了~

**Comment by jljsj33** [comment]
找个问题了，，我的失误，加了可判断参数却还用 import 进来的去判全等。。。，忘改了。。。谢谢

**Comment by jljsj33** [comment]
还有你的 scroll-anim 升级下。。。用1.0.x,,, 删除 hideProps

**Comment by zidoshare** [comment]
解决了，相当感谢~
