### ISSUE TITLE
连续动画怎么解决

### ISSUE THREAD

**Issue by taohailin** [ant-design/ant-motion#72]
单元素动画没得监听动画结束的方法迈，我需要一个动画结束了，另外一个元素动画开始怎么做，两个元素的动画没法用时间轴动画来做

**Comment by jljsj33** [comment]
你说的是一个元素多个动画吗？。。。直接数组就是了。。。。animation={[{x: 100}, { y: 100}]}

**Comment by jljsj33** [comment]
多个用onStart. onComplete。。。https://github.com/react-component/tween-one/blob/master/README.md

**Comment by jljsj33** [comment]
或onChange

**Comment by jljsj33** [comment]
加 delay 也能做的。。。
