### ISSUE TITLE
对动画的学习较困难，文档demo和api不对应。

### ISSUE THREAD

**Issue by yaoxiong** [ant-design/ant-motion#73]
首先很感谢大神们能出这样的框架，能让我们很简单的实现各种动画。
但是使用和学习过程确实不是那么顺畅，也许我能力也不足吧。
用里面的demo写个动画不难，但是当想写深刻点的demo的时候，api的各种参数不全，而且很关键的参数没有解释，很难学习。
打个比方，最简单的单元素动画。demo里animation参数会给我们rotate: 360这样的参数，但是在api中没有任何关于可以使用哪些属性的描述。倒是在http://react-component.github.io/tween-one/里会有有些许的描述。既然是官网，能对api文档有个详细的描述也能让我们更好的学习。

**Comment by jljsj33** [comment]
额。。这个我咋说呢。。。。动画对 css 的处理，，css 里的参数如：left, right, translateX 之类的我在 ant motion 里就没写进 API 里面了。。。不过在 https://github.com/react-component/tween-one 这里我还是有写的:
API 里有这条...
|name	|type|	default	|description|
|---|---|---|---|
|in style	|string / number	|null	|CSS style value: translateX rotateX color marginTop or grayScale, sepia, hueRotate, invert, brightness, contrast, blur or gsap: x y...|

**Comment by afc163** [comment]
去搞个动画术语定义。

**Comment by jljsj33** [comment]
我写了些基本动画需用到的参数变量，可供参考，如果有误，可直接 PR 修改....

https://github.com/react-component/tween-one/blob/master/animate-param.md

**Comment by afc163** [comment]
加到 motion.ant.design 上呀，给设计师做普及用。

**Comment by jljsj33** [comment]
这个加到哪去啊？？？放API里用??

**Comment by afc163** [comment]
https://motion.ant.design/language/basic 这里，加一个动画术语

**Comment by jljsj33** [comment]
这个只是针对 tween-one 的一批参数

**Comment by afc163** [comment]
你可以写的抽象一点，把常用的英文术语提出来描述一下。

**Comment by yaoxiong** [comment]
@jljsj33 文档很给力了。感谢。
