### ISSUE TITLE
在路由添加进出场动画，第一次切换路由后动画执行成功，第二次切换路由后执行动画后children消失，第三次切换路由后动画不执行children出现

### ISSUE THREAD

**Issue by wengwengweng** [ant-design/ant-motion#79]
问题描述：
在主要布局处添加进出场动画，第一次切换路由后动画执行成功，第二次切换路由后执行动画后children消失，第三次切换路由后动画不执行children出现。
完整代码地址：
https://github.com/wengwengweng/react-mobile/tree/weng
局部代码：

```

import QueueAnim from 'rc-queue-anim';

class Layout extends React.Component {

    constructor (props) {

        super(props);

    }

    render () {
 
        return (
            <div>

                <QueueAnim>
                    {childrenWithProps}
                </QueueAnim>

            </div>
        );
    }
}
```
图片对比：
![Uploading 屏幕快照 2017-04-20 上午12.56.08.png…]()
![Uploading 屏幕快照 2017-04-20 上午12.56.23.png…]()

**Comment by jljsj33** [comment]
用 rc-tween-one TweenOneGroup, 这个对多次渲染有处理，，queue-anim 没处理。。后面有空再忧化。。。

**Comment by jljsj33** [comment]
3.0 router Link 每次点击后都渲染两遍。。。

**Comment by jljsj33** [comment]
https://github.com/react-component/queue-anim/issues/35

**Comment by wengwengweng** [comment]
好的 现在改用react的ReactCSSTransitionGroup来做路由过渡动画了😂

**Comment by jljsj33** [comment]
一样的。。。rc-animate 也可以做这样的过渡。。单个的动画，queue-anim 没啥效果的，，

**Comment by wengwengweng** [comment]
好的，十分感谢😊
