### ISSUE TITLE
动效模板无法保存编辑

### ISSUE THREAD

**Issue by dicklwm** [ant-design/ant-motion#81]
当我修改了许多参数配置之后，我打算保存编辑，但是点击保存没有反应，也没有报错提示
- 我猜想应该是URL路径太长导致的无法保存，因为URL的路径是有长度限制的

**Comment by jljsj33** [comment]
恩，，，谢谢，，，这问题看这网站模板的需求要再考虑。。。

**Comment by dicklwm** [comment]
这个网站做公司的静态网站主页很有用，但是就是保存不了，很痛苦

**Comment by jljsj33** [comment]
暂时先用模板内容，下载下去再做编辑吧。。。
