### ISSUE TITLE
网站上有个错别字

### ISSUE THREAD

**Issue by Bruce-Carl** [ant-design/ant-motion#82]
由于是个小问题也不影响阅读，犹豫了一会，最后决定还是说一下
![image](https://cloud.githubusercontent.com/assets/18041237/25649416/0a85aa68-3008-11e7-94a0-a12c4e7e1e75.png)

**Comment by jljsj33** [comment]
谢谢。。。如果你有时间，PR 修改一下就更好。。哈哈 @Bruce-Carl

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-motion/pull/85
