### ISSUE TITLE
请问我如何用自己的logo做成你们案例那样圆点的动效？

### ISSUE THREAD

**Issue by libocheng** [ant-design/ant-motion#86]

**Comment by jljsj33** [comment]
https://motion.ant.design/exhibition/demo/logo-gather-anim, 替换里面的 svg 图片即可。

**Comment by jljsj33** [comment]
这原理是，把图片绘在 canvas 上，，然后获取图片的像素点。。再把圆点的坐标设置成像素点的坐标即可

**Comment by libocheng** [comment]
我是设计，不懂代码，能加你微信细聊吗？

**Comment by jljsj33** [comment]
我也是设计师，，哈哈，，你还是找个码农吧，，你自个是不好搞的。。。

**Comment by libocheng** [comment]
好的，谢谢喽
