### ISSUE TITLE
BannerAnim经常出现卡顿现象，然后切换不了画面？

### ISSUE THREAD

**Issue by VieZhong** [ant-design/ant-motion#87]
使用BannerAnim的时候，无论是手动切换还是自动播放，一开始是正常的，但多次切换画面(Element)之后，很容易会使BannerAnim卡住，不知道这是什么情况？

这是代码：
![qq 20170526090935](https://cloud.githubusercontent.com/assets/16253049/26476691/079244cc-41f3-11e7-9e1a-5ec37d8634f2.png)

这是失败后的样子：
![qq 20170526090845](https://cloud.githubusercontent.com/assets/16253049/26476675/e9f89678-41f2-11e7-8e1b-c7b33df09d62.png)

**Comment by jljsj33** [comment]
我看下

**Comment by VieZhong** [comment]
所以这是什么回事？是我写得有问题吗？可是是按照官网的例子来的呀？

**Comment by jljsj33** [comment]
我在排查，，，，我这边切了几次没问题。。。你是怎么操作的，，，代码贴一下

**Comment by VieZhong** [comment]
![qq 20170526144934](https://cloud.githubusercontent.com/assets/16253049/26483996/8cecdb76-4222-11e7-9888-a1da3c1c90e3.png)

**Comment by VieZhong** [comment]
就是反复多次点下面的5个点点，然后就卡住了。
代码要复制么？但是格式不好控制啊。

**Comment by VieZhong** [comment]
`<BannerAnim prefixCls={styles["banner-project"]} arrow={false} autoPlay autoPlaySpeed={5000}>
                {[imgUrl1,imgUrl2,imgUrl3,imgUrl4,imgUrl5].map((imgUrl, i) => (
                    <Element 
                        prefixCls={styles["banner-project-elem"]}
                        key={i}
                    >
                        <BgElement 
                            key="bg" 
                            className={styles["banner-project-bg"]}
                            style={{backgroundImage: `url(${imgUrl})`}} 
                        />
                        <div key="text" className={styles["banner-project-text"]}>
                            The Fast Way Use Animation In React
                        </div>
                    </Element>
                ))}
            </BannerAnim>`

**Comment by jljsj33** [comment]
http://react-component.github.io/banner-anim/examples/simple.html，这里的没问题啊，，代码复制到我本地也没问题啊。。

**Comment by BeckyWang** [comment]
我也出现了这样的问题，必须改变屏幕的size，图片才会正常轮播 @jljsj33

**Comment by BeckyWang** [comment]
![image](https://user-images.githubusercontent.com/20333434/26911102-c0be310a-4c3d-11e7-808e-699a1a8f41fd.png)
这是图片轮播出错时，dom树的第二个节点为空，改变屏幕的size后，就恢复正常 @jljsj33

**Comment by jljsj33** [comment]
@BeckyWang 把你的背景样式截出来看看。。。 class="_2WkWu*******"这个

**Comment by jljsj33** [comment]
背景是需要样式：
这是默认的：
```
.banner-anim-elem .bg {
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
    overflow: hidden;
}
```

**Comment by BeckyWang** [comment]
```
.banner-project-elem {
        text-align: center;
	color: #fff;
	position: relative;
	overflow: hidden;
}

.banner-project-bg {
	width: 100%;
	height: 100%;
	position: absolute;
	top: 0;
	left: 0;
	overflow: hidden;
	background-size: cover;
	background-position: center;
}
```
样式是按照官网上写的 @jljsj33

**Comment by jljsj33** [comment]
@BeckyWang 方便把代码贴出来，或打包发我邮箱看看。。。我本地没什么问题。。。

**Comment by jljsj33** [comment]
155259966@qq.com

**Comment by jljsj33** [comment]
https://codepen.io/jljsj33/pen/WOQdjB 你重现一下看看

**Comment by jljsj33** [comment]
dom 生成必须要 BannerAnim render 之前。。。不然取不出高度，，所以会导至空白切换。。。
