### ISSUE TITLE
react-routerv4中怎么实现路由切换的进出场效果。

### ISSUE THREAD

**Issue by yangguoquan** [ant-design/ant-motion#91]
QueueAnim
如果包含router。没有渲染的router是没有dom节点存在的

**Comment by jljsj33** [comment]
http://react-component.github.io/queue-anim/examples/router.html#/home

**Comment by mortSoudain** [comment]
Hi! im using react router, and the transitions just doesnt work.

Here is my code:
`import { Meteor } from 'meteor/meteor';
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { Switch, Route } from 'react-router-dom';

import { createContainer } from 'meteor/react-meteor-data';

import Home from './Home.jsx';
import EventosComponente from './Eventos/EventosComponente.jsx';
import SolicitudesComponente from './Solicitudes/SolicitudesComponente.jsx';

import QueueAnim from 'rc-queue-anim';


export default class Contenido extends Component {

  render() {
    return (

      <div className="container">
        <Switch>
          <QueueAnim type={['right', 'left']} className="router-wrap">
            <Route exact path='/' component={Home} />
          </QueueAnim>
          <Route path='/eventos' component={EventosComponente} />
          <Route path='/solicitudes' component={SolicitudesComponente} />
        </Switch>
      </div>
    );
  }
}
`

Does anyone know how to integrate these 2? Thanks!

**Comment by baixiaoji** [comment]
@mortSoudain   you must use the key in the child component, and having one child component you need using the [rc-tween-one](https://motion.ant.design/components/tween-one)
