### ISSUE TITLE
通过display控制div的显示和隐藏，这种情况下如何加动画啊~

### ISSUE THREAD

**Issue by JesseZhao1990** [ant-design/ant-motion#92]

**Comment by jljsj33** [comment]
你为什么要通过 display 来显示隐藏呢，，清楚 children 不更简单???

这是通过 display 来隐藏的: http://react-component.github.io/animate/examples/simple.html

**Comment by JesseZhao1990** [comment]
谢谢你给出demo~~，通过display来显示隐藏主要是基于性能方面考虑的，因为div里有太多太多的节点和逻辑，移除和添加会影响性能。
