### ISSUE TITLE
源码运行 mac pro  下报错

### ISSUE THREAD

**Issue by spiroo** [ant-design/ant-motion#95]
![2017-06-29 2 57 09](https://user-images.githubusercontent.com/7858201/27675177-87833e9a-5cdb-11e7-80f1-23f93a35e284.png)

使用的·cnpm安装，用·npm好像总提示找不到某个依赖。

**Comment by jljsj33** [comment]
？？？

我看下。。。

**Comment by jljsj33** [comment]
升级下 react 就可以了....

```
"react": "15.6.x",
"react-dom": "15.6.x",
```

**Comment by jljsj33** [comment]
冲突了
