### ISSUE TITLE
源码运行 windows 10 下报错

### ISSUE THREAD

**Issue by spiroo** [ant-design/ant-motion#96]
![tim 20170629151109](https://user-images.githubusercontent.com/7858201/27675587-3e84cdf6-5cdd-11e7-9c5f-4fe742b4a449.png)
![tim 20170629151121](https://user-images.githubusercontent.com/7858201/27675589-3eff6638-5cdd-11e7-9e8a-7d9b19e61b40.png)

**Comment by jljsj33** [comment]
win 下运行不了，，毕升的版本问题。。。

https://github.com/ant-design/ant-motion/issues/50
